Added delete button in data set propreties in workbench
specify/specify7 pull request #2755
Opened 2023-01-06 20:06 UTC by CarolineDenis

Fixed #1836

2023-01-06 23:04 UTC, maxxxxxdlp requested changes

2023-01-06 23:04 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/WorkBench/DataSetMeta.tsx
> +                  return users === undefined ? null : isChanged ? (
Looks like the code was reformatted inconsistently.
Could you configure the Prettier plugin (https://github.com/specify/specify7/tree/production/specifyweb/frontend/js_src#plugins) in your IDE and reformat this file with it?

2023-01-11 03:06 UTC, merged

2023-01-11 03:20 UTC, maxxxxxdlp commented on .prettierrc.js
> +module.exports = {
I have just noticed that this file was added. I don't think it is needed
@CarolineDenis does prettier work for you even if this file is removed?

I don't think it is looking at this file as long as we have a "prettier" key in package.json. You need to remove either one of them

2023-01-18 23:02 UTC, specifysoftware commented
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-4-announcement/999/1