Add minLength and maxLength to text input
specify/specify7 pull request #2851
Opened 2023-01-19 17:24 UTC by CarolineDenis

Fixed #2022 

!branch created from "xml-validation" branch.

2023-01-19 18:23 UTC, maxxxxxdlp approved these changes

2023-01-23 03:55 UTC, grantfitzsimmons requested changes
With the form definition as follows ([link](https://newmexico-issue-2022.test.specifysystems.org/specify/resources/view-set/1/)):
```xml
<cell type="field" id="1" name="catalogNumber" uitype="formattedtext" colspan="3" initialize="minLength=9,maxLength=9"/>
```

<img width="483" alt="image" src="https://user-images.githubusercontent.com/37256050/213963303-d09efa35-5f4d-4f62-8c8b-26545947e561.png">

`minLength` is working, but `maxLength` is not.

<img width="529" alt="image" src="https://user-images.githubusercontent.com/37256050/213963340-e4b1f2f2-f772-4ea6-8931-9a0537a58255.png">

2023-01-23 21:08 UTC, grantfitzsimmons approved these changes

2023-01-24 20:51 UTC, grantfitzsimmons commented
Once the tests are fixed, we can merge

2023-01-27 20:10 UTC, merged