Show field caption in query builder
specify/specify7 pull request #2938
Opened 2023-02-03 19:00 UTC by CarolineDenis

Fixed #2901 

For failing tests, copy only screen shots for errors + error explanation and what should be the expected result.

2023-02-03 19:02 UTC, maxxxxxdlp approved these changes

2023-02-04 00:23 UTC, grantfitzsimmons requested changes
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/37256050/216734434-36fc92a6-d9c9-4dea-ba14-269bce7b9ff7.png">

https://sanbibiobank-issue-2901.test.specifysystems.org/specify/query/183/
Username: `kim`
Collection: `Individuals`

This issue is still present on this PR

2023-02-04 01:40 UTC, maxxxxxdlp commented
@grantfitzsimmons for the above screenshot, what's are the expected column headings?

2023-02-04 01:40 UTC, maxxxxxdlp commented
Edit: oh I see, the "Other ID" column is shown as "Collection Object"

2023-02-07 15:34 UTC, grantfitzsimmons requested changes
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/37256050/217289747-6ce3a4b2-b80b-477d-b5ad-ecb6b55ea65c.png">

What is the criteria for prefacing the caption with "Collection Object"?

<img width="630" alt="image" src="https://user-images.githubusercontent.com/37256050/217289881-660ab068-e71d-4e82-923e-d073a2df84e1.png">

For reference, none of these have "Collection Object" before them in the field caption and they are not relationships.

https://sanbibiobank-issue-2901.test.specifysystems.org/specify/query/183/

2023-02-07 16:05 UTC, maxxxxxdlp commented
@grantfitzsimmons the criteria haven't changed since 7.7 so this pull request should not be rejected for that reason. But, feel free to open a new issue.

The current criteria:
If field label is just one word, and the field is not one of the ones listed below, than it is considered generic:

```js
[
  'latitude1',
  'longitude1',
  'latitude2',
  'longitude2',
  'action',
  'fields',
]
```

By generic I mean field label by itself would be ambiguous and table name needs to be included too. The "field label is just one word" rule is very general and exceptions would likely be necessary, though it's a good rule of thumb for a lot of situations. Do you want me to send you the list of all the fields that have a one word label in the default en localization so that you can check if we should mark any of them as not generic?

We can also force some fields to be considered generic. The current list is:
```js
[
  'timestampCreated',
  'timestampModified',
  'createdByAgent',
  'modifiedByAgent',
  'guid',
  'version',
  'id',
]
```

2023-02-07 18:13 UTC, grantfitzsimmons commented
Sure! That sounds good. We can approve this PR then, it is working as intended.

2023-02-07 18:13 UTC, grantfitzsimmons approved these changes

2023-02-07 18:25 UTC, maxxxxxdlp requested changes
Tiny change. After that good for merging

2023-02-07 18:25 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/WbPlanView/mappingPreview.ts
> +  // 'name',
Don't comment it out. Rather, remove it entirely.
Don't want to end up like sp6 with a ton of commented-out code that no one knows what do to with

2023-02-08 15:18 UTC, maxxxxxdlp approved these changes

2023-02-08 15:19 UTC, merged