Offer the possibility to customize the query export delimiter
specify/specify7 pull request #3019
Opened 2023-02-20 18:21 UTC by CarolineDenis

Fixed #2849

2023-02-20 18:27 UTC, maxxxxxdlp approved these changes

2023-02-20 19:47 UTC, chanulee1 requested changes
Query export delimiter customization option is present. But, exported csv files appear to be identical regardless of which option is selected.

Semicolon: 
[query_results_2023-02-20T19_41_11.816867.csv](https://github.com/specify/specify7/files/10787397/query_results_2023-02-20T19_41_11.816867.csv)

Space:
[query_results_2023-02-20T19_44_17.265078.csv](https://github.com/specify/specify7/files/10787410/query_results_2023-02-20T19_44_17.265078.csv)

2023-02-21 04:19 UTC, maxxxxxdlp approved these changes

2023-02-22 19:37 UTC, chanulee1 approved these changes
Appears to be working!

2023-02-22 19:40 UTC, merged