All to populate number of prep in loans with bulk value
specify/specify7 pull request #3044
Opened 2023-02-23 21:52 UTC by CarolineDenis

Fixed #2549

2023-02-24 02:58 UTC, maxxxxxdlp requested changes

2023-02-24 02:58 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/Interactions/PrepDialog.tsx
> +                  onValueChange={(newSelected): void =>
Can just replace this with `onValueChange={setBulkValue}`

2023-02-24 02:58 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/localization/query.ts
> -    'es-es': `
Was this removed accidentally?

2023-02-24 02:58 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/Interactions/PrepDialogRow.tsx
> +            value={
This (very complicated) logic only affects what's visible in the field, not what's going to be sent to the server when user submits the form

2023-02-24 02:58 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/Interactions/PrepDialogRow.tsx
> +            value={
You shouldn't have to change anything in this file.
Instead, in the `onValueChange` for the bulk value input field, call setSelected to change how many are selected in each

2023-02-24 02:58 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/localization/common.ts
> +    'en-us': 'Bulk value',
Rename to `Bulk Select`

2023-02-24 16:46 UTC, maxxxxxdlp approved these changes
@grantfitzsimmons can you take a look and see if you like the position of the bulk select input field? Or should it be above the table?

2023-03-09 18:18 UTC, grantfitzsimmons commented
I think it should be above the table, but it looks good!

My only request would maybe be that when "Select All" is selected the Bulk Select goes to its max value.

2023-03-09 18:19 UTC, grantfitzsimmons approved these changes

2023-03-09 18:19 UTC, grantfitzsimmons commented
Don't merge until @chanulee1 has had some time to test as well

2023-03-10 01:56 UTC, chanulee1 requested changes
Does not select preparations for initial count of bulk value. Must increment and then decrement to select number of preps equal to the initial count.


https://user-images.githubusercontent.com/103299204/224203330-8e8b1c27-699c-4408-b630-f2998bf4d11a.mp4

https://coldfish-issue-2549.test.specifysystems.org/specify/

2023-03-10 13:49 UTC, grantfitzsimmons commented
> Does not select preparations for initial count of bulk value. Must increment and then decrement to select number of preps equal to the initial count.

The default bulk select value should be 0 instead of 1 so that this issue does not occur

2023-03-10 17:09 UTC, chanulee1 commented
Default bulk select issue is fixed. But, "select all" and "deselect all" buttons do not affect bulk select value. Is this an issue?

https://user-images.githubusercontent.com/103299204/224378863-66585b59-51f8-46f9-9330-842e9a09791e.mp4

2023-03-10 18:55 UTC, CarolineDenis commented
@chanulee1 , The select all should not modify the bulk value

2023-03-13 16:28 UTC, chanulee1 approved these changes

2023-03-13 17:39 UTC, maxxxxxdlp requested changes
I would echo what Grant said and suggest that this is put above the table as it's current position looks weird (because some cells are blank) and is confusing (because it changes the number of rows in the table - which is sort of data misrepresentation)

Can we put it above the table?
ie, something like: `Bulk Select: [_0_______]` (just a label and a field, excuse the ascii art)

2023-03-13 19:30 UTC, maxxxxxdlp approved these changes

2023-03-13 21:20 UTC, merged