Add styling for printing
specify/specify7 pull request #3050
Opened 2023-02-24 21:52 UTC by CarolineDenis

Fixed #2988

2023-02-24 21:53 UTC, maxxxxxdlp requested changes
Merge problems. Otherwise looks good

2023-02-24 21:53 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/localization/query.ts
> -    'es-es': `
Looks like the merge didn't go well once again. Not sure why this keeps on happening.
Do you want to revisit merge conflict resolution on Monday?

2023-02-24 22:03 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/localization/query.ts
> -    'es-es': `
Fixed by removing "virus" merge commits

2023-02-24 22:03 UTC, maxxxxxdlp approved these changes

2023-02-27 19:16 UTC, grantfitzsimmons approved these changes

2023-02-27 19:16 UTC, grantfitzsimmons commented
Works in Firefox, Chrome, and Edge

2023-02-27 19:16 UTC, merged