Add indication for remaining time when validating in workbench
specify/specify7 pull request #3058
Opened 2023-02-27 19:56 UTC by CarolineDenis

Fixed #2034

2023-02-27 20:03 UTC, maxxxxxdlp requested changes

2023-02-27 20:03 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/WorkBench/Status.tsx
> +      if (current > 15) {
Don't just put magic numbers in the code.
Create a variable right above the component, and add a comment on top of the variable describing what it's used for

2023-02-27 20:03 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/WorkBench/Status.tsx
> +            (((total - current) / current) * (Date.now() - startTime.current)) /
(optional) this expression could be split into multiple variables to make it more readable

2023-02-27 20:03 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/WorkBench/Status.tsx
> +  // Convert seconds to minutes and seconds and create returned string
This function should not be defined inside a component as it doesn't have any logic specific to this component - it's just a utility. Move it into `./Atoms/Internalization.tsx` or `./utils/utils.ts`

2023-02-27 20:09 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/WorkBench/Status.tsx
> +      if (current > 15) {
For context, wiki page about [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming))

2023-02-27 22:25 UTC, maxxxxxdlp approved these changes

2023-02-28 17:34 UTC, chanulee1 approved these changes
Timer for validation present.

2023-02-28 21:35 UTC, merged

2023-03-02 02:13 UTC, specifysoftware commented
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-7-release-announcement/1079/1