Split spdataset rowresults
specify/specify7 pull request #3066
Opened 2023-03-01 06:39 UTC by acwhite211

Split up the spdataset rowresults into a separate table to avoid large field values and avoid exceeding the max_allowed_packet size during database backups.

2023-03-01 17:17 UTC, maxxxxxdlp commented
Please tell when code is ready for review

2023-03-08 16:33 UTC, maxxxxxdlp requested changes
Looks like most of the code is copied from https://github.com/specify/specify7/pull/1045

Is there a reason a new PR was created rather than extending that one?

2023-03-08 16:33 UTC, maxxxxxdlp commented on specifyweb/workbench/migrations/0009_spdataset_add_lock_table.py
> +    operations = [
Just curious, why was a new table created for this?

2023-03-08 16:33 UTC, maxxxxxdlp commented on specifyweb/workbench/upload/upload.py
> +    # TODO: The following can be replaced with connections.create_connection(...)
Django has been updated to v3.2.1. Can this be replaced now?

2023-03-08 16:33 UTC, maxxxxxdlp commented on specifyweb/workbench/upload/upload.py
> +                yield r.data
(optional) Optimization according to ChatGPT:

```py

    def rows():
        last_rownumber = -1
        while True:
            rs = ds.rows.filter(rownumber__gt=last_rownumber)[:1000]
            if not rs:
                break
            for r in rs:
                last_rownumber = r.rownumber
                yield r.data
```

2023-03-21 14:43 UTC, grantfitzsimmons commented
https://archireef-split-spdataset-rowresults.test.specifysystems.org/specify/workbench/7/

In the console I am getting the following error when I have this data set opened:

```
Object { type: "jsonParseFailure", statusText: "Failed parsing JSON response:", responseText: "ok" }
interceptLogs.ts:88:6
```

I am also unable to even attempt an upload, though validation seems to run correctly.

2023-03-21 14:51 UTC, grantfitzsimmons requested changes
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/37256050/226644615-ed6f5b6c-c926-4e31-9402-7263414ff329.png">

https://archireef-split-spdataset-rowresults.test.specifysystems.org/specify/workbench/7/

I am unable to run an upload and continue to get the following error:
```
Object { type: "jsonParseFailure", statusText: "Failed parsing JSON response:", responseText: "ok" }
​
responseText: "ok"
​
statusText: "Failed parsing JSON response:"
​
type: "jsonParseFailure"
​
<prototype>: Object { … }
interceptLogs.ts:88:6

```

2023-10-10 17:58 UTC, CarolineDenis commented
@acwhite211 @grantfitzsimmons Could we start to work on this again?

2023-10-10 18:00 UTC, grantfitzsimmons commented
We made an [announcement to fix it December 8, 2022](https://discourse.specifysoftware.org/t/important-specify-database-backups-can-fail/927).

We said this:
> We are scheduling that fix for January 2023.

2026-05-18 17:14 UTC, acwhite211 commented
This PR is pretty far out of date now, but this idea for splitting up the spdataset rowresults into multiple rows might be a good idea in the future.

2026-05-18 17:14 UTC, closed without merging