Align paginator on the right
specify/specify7 pull request #3118
Opened 2023-03-08 15:40 UTC by CarolineDenis

Fixed #3101

2023-03-08 16:47 UTC, maxxxxxdlp approved these changes

2023-03-08 18:33 UTC, chanulee1 requested changes
Still appears to be on the left.

![image](https://user-images.githubusercontent.com/103299204/223803214-a153e0fa-d1eb-4ce1-8336-ed3374aa4c27.png)

https://coldfish-issue-3101.test.specifysystems.org/specify/query/128/

2023-03-08 19:58 UTC, CarolineDenis commented
Appears on the right for me. Can you let me know where this issue happens? 
<img width="1192" alt="Screenshot 2023-03-08 at 11 56 44 AM" src="https://user-images.githubusercontent.com/108160931/223832966-cfc2fbe6-1af7-4ae0-8686-bc023c300e3a.png">

2023-03-09 16:36 UTC, chanulee1 commented
@CarolineDenis It happens when using the "Browse in Forms" option in the query results. Tested it on this deployment on the test panel: https://coldfish-issue-3101.test.specifysystems.org/specify/query/128/

2023-03-13 21:42 UTC, merged