Fix scroll bar when exporting to TSV
specify/specify7 pull request #3260
Opened 2023-03-28 14:29 UTC by CarolineDenis

Fixes  #2733

2023-04-04 01:04 UTC, grantfitzsimmons requested changes
https://user-images.githubusercontent.com/37256050/229659718-223d4e01-f754-4b5f-b637-009eb7da8ffb.mov

I still see the issue

https://herbrbge33123-issue-2733.test.specifysystems.org/specify/stats

Firefox, macOS

2023-04-04 20:11 UTC, CarolineDenis commented
@grantfitzsimmons can you test this to see if it makes any difference?

2023-04-04 22:55 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/Molecules/FilePicker.tsx
> +    iframe.classList.add('absolute', 'hidden');
I was hesitant to add `'hidden'` as some browsers might not trigger file downloads from hidden iframes.
Just adding `absolute` might be sufficient to fix this issue.

2023-04-05 14:05 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/Molecules/FilePicker.tsx
> +    iframe.classList.add('absolute', 'hidden');
`'hidden'` only affects visibility, not the placement. Presence or absence of scroll bar should not be affected by it.

Doesn't the scroll bar disappear as soon as you add `'absolute'`? If not, you might need to add `top-0` or something like that

2023-04-05 14:13 UTC, CarolineDenis commented
@maxxxxxdlp 
With absolute + hidden: 

https://user-images.githubusercontent.com/108160931/230107942-38d887b4-a1fc-4f30-b138-a0a095545454.mov

with absolute: 
![Screenshot 2023-03-30 at 2 36 26 PM](https://user-images.githubusercontent.com/108160931/230108003-d98dc883-7a12-44a2-bcf0-b703d5f2e5ae.png)

2023-04-05 14:21 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/Molecules/FilePicker.tsx
> +    iframe.classList.add('absolute', 'hidden');
the 2nd video in your comment doesn't load for me, but I trust you

Interesting that there is not a single mention of scroll bars on the wiki page for visibility:hidden - https://developer.mozilla.org/en-US/docs/Web/CSS/visibility

2023-04-05 14:21 UTC, maxxxxxdlp approved these changes

2023-04-05 14:26 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/Molecules/FilePicker.tsx
> +    iframe.classList.add('absolute', 'hidden');
keep the hidden. as otherwise there is no point in these changes if they don't fix the scroll bar

2023-04-06 15:00 UTC, grantfitzsimmons approved these changes

2023-04-06 15:02 UTC, merged