Add link to CO and Taxon for preparations in interaction dialog
specify/specify7 pull request #3261
Opened 2023-03-28 17:12 UTC by CarolineDenis

Fixes #2718

2023-03-28 17:19 UTC, maxxxxxdlp requested changes

2023-03-28 17:19 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/Interactions/InteractionDialog.tsx
> +        coId: prepData[1],
Replace with `collectionObjectId`. Please don't use contraction in this codebase in the future it's not always clear what was meant by it.

Case in point, do you have an idea of what our previous engineer meant by `LDLM` in `LDLM_TO_MYSQL`? No other references to it in the codebase or online

2023-03-28 17:19 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/Interactions/PrepDialogRow.tsx
> +              href={`/specify/view/collectionobject/${preparation.coId}`}
Use `getResourceViewUrl('CollectionObject', preparation.collectionObjectId)` instead.
Reason: it's easy to make a typo in a string or forget a `/`, but when calling getResourceViewUrl everything is safe:
1. TypeScrpipt checks that getResourceViewUrl is a correct name of the function
2. TypeScript checks that 'CollectionObject' is a valid table name
3. TypeScript checks that preparation.collectionObjectId is a number
4. In the future, if we want to change the URL, we just have to change the function and all the places are updated automatically!

2023-03-28 17:30 UTC, maxxxxxdlp approved these changes

2023-03-29 20:44 UTC, realVinayak commented
https://user-images.githubusercontent.com/61122018/228662733-a8535808-0293-4ccb-a7bf-501b64547143.mp4

Clicking on record set doesn't open interactions dialog at all.

2023-03-30 01:13 UTC, CarolineDenis commented
> Clicking on record set doesn't open interactions dialog at all.

This behavior was the behavior previous to this PR. You cannot 'click'/open a record set if it doesn't contain any preparation to loan.

2023-03-30 01:19 UTC, realVinayak commented
Ah, thanks for clearing that up for me!

2023-04-04 01:16 UTC, grantfitzsimmons approved these changes
I wouldn't merge yet as we go into the next couple of releases, but post-`statspage` I am excited to see this feature!

Works great!

2023-04-05 17:31 UTC, merged