Update new form definition title
specify/specify7 pull request #3262
Opened 2023-03-28 17:54 UTC by CarolineDenis

Fixes #2694

2023-03-28 18:06 UTC, maxxxxxdlp requested changes

2023-03-28 18:32 UTC, maxxxxxdlp approved these changes

2023-03-29 21:16 UTC, realVinayak commented
https://user-images.githubusercontent.com/61122018/228669395-9a68a78d-2209-4e29-b1af-50f0b0cf9b8e.mp4

Shouldn't say 'New Form Definition' for any resource

2023-04-04 01:01 UTC, grantfitzsimmons approved these changes
Wait to merge this, but it looks good!

2023-04-05 17:30 UTC, merged