Allow to enter data into any search field after dragging
specify/specify7 pull request #3272
Opened 2023-03-29 17:27 UTC by CarolineDenis

Fixes #3269

2023-03-29 19:30 UTC, chanulee1 requested changes
Able to drag query line when hovering over a button.


https://user-images.githubusercontent.com/103299204/228647424-0536f0e8-a208-424a-ad90-ca5facd1f3ef.mp4

https://coldfish-issue-3269.test.specifysystems.org/specify/query/128/

2023-03-29 19:42 UTC, maxxxxxdlp commented
Drag and drop when hovering over list boxes was allowed because it didn't cause bugs (in our testing)
Drag and drop for buttons should have been disabled - @CarolineDenis take a look at why it's not fixed

2023-03-30 16:22 UTC, realVinayak commented
I can still reproduce it 
![image](https://user-images.githubusercontent.com/61122018/228901411-cbbe9b17-33ac-4a1d-af26-c028acaf6086.png)

2023-03-30 17:06 UTC, CarolineDenis commented
> I can still reproduce it
> ![image](https://user-images.githubusercontent.com/61122018/228901411-cbbe9b17-33ac-4a1d-af26-c028acaf6086.png)

I think this was fixed in the new commit

2023-03-30 22:33 UTC, maxxxxxdlp commented
> I can still reproduce it

@realVinayak you should reject the commit in such cases. That then gives owners of the PR option to request re-review which would send you a notification

2023-03-30 22:35 UTC, maxxxxxdlp requested changes

2023-03-30 22:35 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/QueryBuilder/Fields.tsx
> +        target.closest('button') !== null ||
Change to loop over an array

2023-03-30 22:35 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/QueryBuilder/Fields.tsx
> +        target.closest('article') !== null
'article' can be used for several things, not just by combo box. if you want to match combo box, replace `article` with `.custom-select`

2023-03-31 01:17 UTC, maxxxxxdlp approved these changes

2023-03-31 14:10 UTC, realVinayak commented
Not sure if this should be fixed in the PR or not but when using drag query fields in a dialog, the fields are behind the dialog. 
![Screenshot (66)](https://user-images.githubusercontent.com/61122018/229144097-7ff8acb6-4b43-4129-98ab-b6219f61faa3.png)

2023-03-31 14:16 UTC, realVinayak commented
Also, sometimes, when using drag in the dialog, the field lines sometimes jump outside of the dialog. Like this:
![image](https://user-images.githubusercontent.com/61122018/229144622-56751e14-0b25-4c25-9c26-00b0143354c0.png)
I'm aware that is the `edge`, but that is irrelevant because you are just canceling  the events in the PR, so this will still be reproducible. I haven't found a conclusive way to reproduce this. @CarolineDenis can you go through the code and see why this might happen? Also, this remains on the screen even if go to a different page 
![image](https://user-images.githubusercontent.com/61122018/229145325-e40dc77c-354f-41fa-870c-84938b92f652.png)
![image](https://user-images.githubusercontent.com/61122018/229145106-746f571e-8869-4e68-98f2-960ba9ff2bf3.png)
![image](https://user-images.githubusercontent.com/61122018/229145445-946ad6a6-3787-4831-80f3-a5e0b886de09.png)

2023-03-31 14:43 UTC, realVinayak commented
Extensively tested this, works for me. @chanulee1 can you do another round and see if you catch anything weird related to this PR?

2023-03-31 20:32 UTC, chanulee1 approved these changes
Did not find anything weird. Cannot drag query lines by buttons or inputs.

2023-03-31 20:58 UTC, merged