Fix query combo box not scoping created resources to other collection
specify/specify7 pull request #3283
Opened 2023-03-31 21:50 UTC by maxxxxxdlp

Fixes https://github.com/specify/specify7/issues/2405
Fixes https://github.com/specify/specify7/issues/3078
Also, allows unhiding all fields in autogenerated forms (in the meta menu when you say "use autogenerated form", there is now also a new checkbox)

Theresa was correct - there is a generic solution to this to fix it in all places

2023-04-04 00:49 UTC, grantfitzsimmons commented
https://github.com/specify/specify7/issues/3293

This issue is severe enough that it may be necessary to forbid creating new taxon records and only offer the ability to associate existing ones.

2023-04-04 00:50 UTC, grantfitzsimmons requested changes
Consider removing the ability to create records in the destination discipline as the form uses elements from the current discipline. Only the query combo box is searching the destination tree.

2023-04-28 22:08 UTC, chanulee1 requested changes
Still seem to be unable to set batch of agents for collection access. Setting agents and saving clears the fields.

https://user-images.githubusercontent.com/103299204/235262056-4ed70182-3cb7-4f52-a820-7e9789241869.mp4

https://herbumass-issue-2405.test.specifysystems.org/specify/security/user/61/

2023-12-11 04:09 UTC, melton-jason commented
> Still seem to be unable to set batch of agents for collection access. Setting agents and saving clears the fields.
> 
>  4TM55lRxIR.mp4 
> https://herbumass-issue-2405.test.specifysystems.org/specify/security/user/61/

Can this (#2405) be tested again?

2024-01-03 17:35 UTC, pashiav requested changes
Page gets stuck on loading popup after clicking **Add User**. Does not happen on `edge`.

https://github.com/specify/specify7/assets/118556884/74cc494a-be51-46be-a545-01bfc83db629

2026-07-21 14:44 UTC, closed without merging