Display available/unavailable preps + allow to choose cat# in loan
specify/specify7 pull request #3438
Opened 2023-05-02 18:55 UTC by CarolineDenis

Fixes #3397

2023-05-03 18:08 UTC, maxxxxxdlp requested changes
Looks like this bug was caused by https://github.com/specify/specify7/commit/ea4d3cf9d

The fix looks good, but I would like to request changes to the files modified in https://github.com/specify/specify7/commit/ea4d3cf9d#diff-40a25e2d48b404baea2f28c969023f392a250be25813d361099e0ce38af72145R68-R92
You check in the code if collection object id is defined. Isn't it always defined, or are the cases when it isn't?
If there are no such cases, delete the needless branch. If there are such cases, then refactor the code to remove duplication (the duplicate `<td>` and call to `syncFieldFormat`)

2023-05-03 19:55 UTC, maxxxxxdlp approved these changes

2023-05-05 18:25 UTC, CarolineDenis commented
Test for: https://github.com/specify/specify7/issues/3453 too. 
Close (https://github.com/specify/specify7/issues/3453) if tests ok

2023-05-16 18:33 UTC, grantfitzsimmons approved these changes

2023-05-16 20:07 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/Interactions/InteractionDialog.tsx
> +    const missing = entries
please please don't do implicit conversion to boolean
do explicit `typeof entries === 'object'` instead to avoid bugs

2023-05-16 20:08 UTC, maxxxxxdlp approved these changes

2023-05-16 20:17 UTC, carlosmbe approved these changes

2023-05-16 20:20 UTC, merged

2023-05-16 21:33 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/Interactions/InteractionDialog.tsx
> +    const missing = entries
given that this is high urgency pull request, @CarolineDenis please open a new pull request with the fix for this lower priority issue

please also keep the implicit vs explicit boolean comparison in mind in the future