Es localization
specify/specify7 pull request #3469
Opened 2023-05-08 20:54 UTC by maxxxxxdlp

Improve Spanish Localization (by `Iñigo Granzow de la Cerda <igranzow@rjb.csic.es>`)

To test:
review the changed files briefly to make sure nothing looks odd (i.e, make sure no stray `)` or `'`' were introduced)

2023-05-10 20:46 UTC, grantfitzsimmons commented on specifyweb/frontend/js_src/lib/localization/forms.ts
> -    'es-es': 'Objeto actual (de {total:number|formatted})',
This is better

2023-05-10 20:47 UTC, grantfitzsimmons commented on specifyweb/frontend/js_src/lib/localization/forms.ts
> -    'es-es': 'Comando N/A',
This is better (maybe keep D?)

2023-05-10 20:48 UTC, grantfitzsimmons commented on specifyweb/frontend/js_src/lib/localization/forms.ts
> -    'es-es': 'Nombre del comando',
better

2023-05-10 20:49 UTC, grantfitzsimmons commented on specifyweb/frontend/js_src/lib/localization/forms.ts
> -    'es-es': 'Valor ilegal para un campo Sí/No',
this is better

2023-05-10 20:51 UTC, grantfitzsimmons commented on specifyweb/frontend/js_src/lib/localization/forms.ts
> -    'es-es': 'Toda la mesa',
See line 643, should be la tabla?

2023-05-10 21:01 UTC, grantfitzsimmons requested changes
Lots of changes we should make– but it looks fine

2023-05-10 21:01 UTC, grantfitzsimmons commented on specifyweb/frontend/js_src/lib/localization/welcome.ts
> +      financiado por múltiples ayudas de U.S. National Science Foundation.
Institution names should be preserved in English

2023-05-12 03:20 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/localization/interactions.ts
> +    'es-es': 'No hay preparaciones sin resolver para  este préstamo.',
fortunately, website has a check for this, just in case Grant is not there to save us 😸

2023-05-12 03:21 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/localization/notifications.ts
> +    'es-es': 'Elemento de fuente de datos para exportación actualizado.',
can you clarify?
the updated string is coming from his localization
you want me to revert it to automated translation?

2023-05-12 19:05 UTC, grantfitzsimmons commented on specifyweb/frontend/js_src/lib/localization/notifications.ts
> +    'es-es': 'Elemento de fuente de datos para exportación actualizado.',
`Fuente de datos` sounded odd, but it seems it is valid. Ignore

2023-05-14 01:10 UTC, maxxxxxdlp commented
@grantfitzsimmons I don't think a PR is the best place for reviewing localization changes.
Weblate is made exactly for that.
If there aren't any other major issues, I propose we merge this and continue further improvements to Spanish localization in Weblate

2023-05-16 20:03 UTC, grantfitzsimmons approved these changes

2023-05-16 20:03 UTC, grantfitzsimmons commented
@maxxxxxdlp Let's merge this and continue in Weblate

2023-05-17 00:40 UTC, merged