Change smallBtn background color when hover to saveBtn
specify/specify7 pull request #3543
Opened 2023-05-30 16:10 UTC by CarolineDenis

Fixes #3535

2023-05-30 19:18 UTC, melton-jason requested changes

2023-05-30 21:50 UTC, CarolineDenis commented
@melton-jason @carlosmbe 
After discussion with @grantfitzsimmons we decided to unify the behavior for all the Button.Small. The background when hovering will be a darker grey in both modes. See videos bellow. 

https://github.com/specify/specify7/assets/108160931/dbf1aa12-5bdc-41fd-95dc-481e17130384




https://github.com/specify/specify7/assets/108160931/671abfa0-15b4-42ea-9c18-0b1c2a78721b

2023-05-30 23:02 UTC, melton-jason commented
> After discussion with @grantfitzsimmons we decided to unify the behavior for all the Button.Small. The background when hovering will be a darker grey in both modes. 

That works for me, as long as there is a consensus :+1:

2023-05-30 23:04 UTC, melton-jason commented on specifyweb/frontend/js_src/lib/components/Atoms/className.ts
> +  smallButton: `${niceButton} !py-1 !px-2 hover:bg-[color:var(--save-button-color)]`,
Resolved in 17d502a

> @melton-jason @carlosmbe After discussion with @grantfitzsimmons we decided to unify the behavior for all the Button.Small. The background when hovering will be a darker grey in both modes. See videos bellow.
> 
>  btns.mov 
>  Screen.Recording.2023-05-30.at.3.05.36.PM.mov

From https://github.com/specify/specify7/pull/3543#issuecomment-1569154335

2023-05-31 21:11 UTC, carlosmbe approved these changes
Looks Good 👍

2023-05-31 21:26 UTC, melton-jason approved these changes

2023-06-01 13:07 UTC, merged

2023-06-05 14:04 UTC, bronwyncombs commented
`v7.8.12-prerelease`: Button.Small works as expected

2023-06-13 16:42 UTC, specifysoftware commented
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-12-release-announcement/1202/1