Improve Specify Network map description
specify/specify7 pull request #3581
Opened 2023-06-06 17:29 UTC by CarolineDenis

Fixes #3552

2023-06-07 02:47 UTC, maxxxxxdlp requested changes

2023-06-07 02:47 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/localization/specifyNetwork.ts
> +      Occurrences recorded in iDigBio are shown as round green points, except for those from the current collection recorded in iDigBio that are round red points. Zooming in on the red points brings
please avoid long lines - those cause horizontal scrolling in an editor
you can enable a feature in your text editor that automatically hard wraps line at 80 characters and you can also configure visual rulers - https://stackoverflow.com/questions/29968499/vertical-rulers-in-visual-studio-code

2023-06-09 04:36 UTC, maxxxxxdlp approved these changes

2023-06-09 13:50 UTC, melton-jason approved these changes

2023-06-09 13:55 UTC, merged

2023-06-09 21:16 UTC, grantfitzsimmons commented
> GeoMap description reads correctly. It could be beneficial to create more of a map key display, especially since this view is hidden initially. Perhaps some bullet points and/or rendering the symbols inline would make it easier for the user to discern them. However, it is perfectly functional at this time.

I agree! You could create a feature request for adding a map key as a new issue so that your thoughts are not lost with this PR :smile: