Unify color scheme on stat page
specify/specify7 pull request #3726
Opened 2023-07-05 19:58 UTC by CarolineDenis

Fixes #3687

2023-07-05 19:59 UTC, CarolineDenis commented
Change the color of headers to be unified with custom color 3
Before: 
![Screenshot 2023-07-05 at 12 57 30 PM](https://github.com/specify/specify7/assets/108160931/3eb1fffb-3d13-4b99-bebb-d4e6ae1a2035)
With new push: 
![Screenshot 2023-07-05 at 12 50 16 PM](https://github.com/specify/specify7/assets/108160931/92d0e086-4d58-4896-84cf-d150e1f2c2af)

2023-07-05 20:06 UTC, CarolineDenis commented
Regarding the button "Collection" being brighter. 
In specify we have a class that makes a button brighter when pressed. With the line `aria-current={isCurrent ? 'page' : undefined}` line 20 in Statistics/Buttons.tsx the button is pressed when selected. 
In other words, the behavior is correct with the current code.
@realVinayak what do think? We could choose to use another button that doesn't add brightness when pressed .

2023-07-06 14:04 UTC, melton-jason approved these changes

2023-07-06 14:58 UTC, bronwyncombs requested changes
Functions correctly! 
Regarding the brightness, though, I did find colors like this. They are decent shades for the category headers and other areas, but too bright on the pressed button. For most colors this is fine, however, I think it should be changed if that can be done easily

![Screen Shot 2023-07-06 at 9 15 54 AM](https://github.com/specify/specify7/assets/135047322/e9c993c9-607b-464d-8242-1dc73356a320)
![Screen Shot 2023-07-06 at 9 12 18 AM](https://github.com/specify/specify7/assets/135047322/5384917b-172a-4d41-acdd-2cef74eb670e)

2023-07-06 15:05 UTC, grantfitzsimmons commented
>Regarding the brightness, though, I did find colors like this. They are decent shades for the category headers and other areas, but too bright on the pressed button. For most colors this is fine, however, I think it should be changed if that can be done easily

I agree with @bronwyncombs – Could we make the color for a selected category the same as the headings? Does this introduce any UI concerns?

2023-07-06 15:29 UTC, CarolineDenis commented
> > Regarding the brightness, though, I did find colors like this. They are decent shades for the category headers and other areas, but too bright on the pressed button. For most colors this is fine, however, I think it should be changed if that can be done easily
> 
> I agree with @bronwyncombs – Could we make the color for a selected category the same as the headings? Does this introduce any UI concerns?

Agree with you, as I explained in my comment above, the color is the same as the headers just that the button is 'pressed'. I am waiting on Vinnie to know what he would like to do with this.

2023-07-06 16:19 UTC, bronwyncombs commented
> I am waiting on Vinnie to know what he would like to do with this.
Yes of course! Totally understand that. I really just wanted to add some more context to your comment for when he thinks it over  ◡̈

2023-07-12 17:49 UTC, bronwyncombs approved these changes
Looks good to me! 
- Button for selected page is no longer pressed automatically, making it more uniform. This also allows for a better view of a wider color selection. 
- A border color is now applied to selected page button (determined by `Secondary button color`) which helps supplement the visual distinction that the pressed button look had. 
- Text color of the page buttons still alternate black and white based on selection status. 
- `Accent color 3` now determines the color of the statistic name when scrolled over in addition to the category headings. (I think this looks nice)

**example of last bullet point**
![Screenshot 2023-07-12 at 12 35 27 PM](https://github.com/specify/specify7/assets/135047322/f8ac3b17-bcf1-4422-8aac-51fe0c08d799)

**general overview**
![Screenshot 2023-07-12 at 12 02 18 PM](https://github.com/specify/specify7/assets/135047322/81264110-cc15-4a82-8301-a0d40c31c655)
![Screenshot 2023-07-12 at 12 04 33 PM](https://github.com/specify/specify7/assets/135047322/bdfd2fa7-5bea-4150-94d0-1c216640ae85)

2023-07-12 18:13 UTC, bronwyncombs requested changes
Hi, so sorry about this. After testing with dark mode I realized that there is a necessary change. As you can see in this screenshot, the unselected button on the bottom, "Personal", is hard to read due to text color. Can you make it so the unselected button text is black like it is in light mode and system settings? Also, the border feature is missing from dark mode. 

![Screenshot 2023-07-12 at 1 00 46 PM](https://github.com/specify/specify7/assets/135047322/9e53c238-ff76-473a-bbad-aee765070c1d)

Further, the color of the buttons when scrolled over is quite contrasting. This does its job, but could be considered too bright for the chosen color. This seems to be the case for all secondary buttons in dark mode. Could you remove this behavior and replace with the border feature of accent color 3 when hovered over?

https://github.com/specify/specify7/assets/135047322/267399d6-fea9-4c6d-a92b-4aeb247ce204

2023-07-12 18:24 UTC, CarolineDenis commented
@bronwyncombs, 

- I can make the text black when not selected :+1:
- We do not have rings in dark mode on the button small 
- We could change the value of the brightness added to the buttons when hovered but it needs to be the same value for all Sp. Note that depending on the color the brightness seems stronger or not. (We cannot handle all the possibilities as the user has all options to change them)

2023-07-12 20:30 UTC, grantfitzsimmons commented
@bronwyncombs Can you give this another look?

2023-07-12 20:34 UTC, bronwyncombs approved these changes
Looks great! 😌 

https://github.com/specify/specify7/assets/135047322/52fa573f-d181-42f1-95b2-49af7342c723

2023-07-12 20:52 UTC, grantfitzsimmons requested changes
<img width="591" alt="image" src="https://github.com/specify/specify7/assets/37256050/9a584db1-c84f-40fc-ba1f-add647d16f4d">

These buttons should not be gray. 
Instead of being the outline color, it should be the button color.

2023-07-13 02:01 UTC, maxxxxxdlp requested changes

2023-07-13 02:01 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/Atoms/className.ts
> +const secondaryButton = `${buttonClassName} hover:brightness-90 dark:hover:brightness-125 bg-[color:var(--secondary-button-color)] text-gray-800 shadow-sm
make sure to do quick testing of at least a few places where secondary and secondary light button is used to make sure the hover effect is visible enough even after this change

2023-07-13 17:45 UTC, grantfitzsimmons approved these changes
Beautiful.

2023-07-13 17:47 UTC, merged