Add search box to splash screen
specify/specify7 pull request #3835
Opened 2023-07-24 21:09 UTC by CarolineDenis

Fixes #3540

2023-07-25 01:35 UTC, maxxxxxdlp requested changes
good job refactoring that into a component and changing styles appropriately

have one suggestion though

2023-07-25 01:35 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/HomePage/index.tsx
> +  const [pendingQuery] = value;
why not move these into the `<SearchForm />`?

`formId` is the only one that is needed outside of it

2023-07-26 02:22 UTC, grantfitzsimmons requested changes
**Can we make it this:**
![image](https://github.com/specify/specify7/assets/37256050/e498c996-b165-446e-921a-25ef8e0ccd42)

**Instead of this:**
![image](https://github.com/specify/specify7/assets/37256050/9925d527-4774-435f-af3b-bea7fa09b6c8)

2023-07-26 04:26 UTC, maxxxxxdlp approved these changes

2023-07-27 03:45 UTC, maxxxxxdlp approved these changes

2023-07-28 20:31 UTC, grantfitzsimmons approved these changes

2023-07-30 14:09 UTC, bronwyncombs approved these changes
Looks good! Working as expected. 

<img width="1436" alt="Screenshot 2023-07-30 at 9 06 37 AM" src="https://github.com/specify/specify7/assets/135047322/1943577a-ceee-496c-949b-46cbe6566b23">

full screen:
<img width="1436" alt="Screenshot 2023-07-30 at 9 07 59 AM" src="https://github.com/specify/specify7/assets/135047322/60b99e25-7713-48f1-bc33-32fc58d5e79d">

2023-07-30 14:24 UTC, bronwyncombs commented
The search box is sized differently across browsers. Could be expected but if it's not: 

<img width="1436" alt="Screenshot 2023-07-29 at 11 25 47 PM" src="https://github.com/specify/specify7/assets/135047322/60e26116-38ad-4d15-a5f1-fec080df2eea">

2023-08-01 20:10 UTC, carlosmbe commented
Does it have a toggle? For example, if a user prefers have a minimalist layout. Can they turn it off? (I am that user)

2023-08-02 16:00 UTC, grantfitzsimmons commented
I am OK with adding a pref, though it is not a priority.

2023-08-04 00:44 UTC, maxxxxxdlp requested changes

2023-08-04 00:44 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/Preferences/UserDefinitions.tsx
> +            description: preferencesText.addSearchBarHomePage(),
if description is the same as title, then why add description at all?
either specify a different description, or remove it

2023-08-15 00:44 UTC, maxxxxxdlp approved these changes

2023-09-26 14:34 UTC, merged