Remove merging capability from forms
specify/specify7 pull request #3842
Opened 2023-07-26 14:44 UTC by CarolineDenis

Fixes #3836

2023-07-26 19:05 UTC, grantfitzsimmons approved these changes

2023-07-26 21:05 UTC, melton-jason requested changes
Not a huge fan of simply removing something because of an issue. 
Finding a solution would be infinitely better.

However, this is not a major component of record merging, and there is considerable pressure to get the release out, which is why this is a barely acceptable change. 

If we do remove a feature from the code, it should be easy to identify what the previous implementation was, and/or why it was removed.

2023-07-27 03:44 UTC, maxxxxxdlp approved these changes
Just like Jason said, I don't like this solution, but for not delaying the release let's have it.

For a proper fix, you can just tell the Search Dialog to exclude the current record using an extra Filter:
https://github.com/specify/specify7/blob/207df9a091c59cd04e4e4b1c3eb111c75c74f68a/specifyweb/frontend/js_src/lib/components/SearchDialog/index.tsx#L56

---

edit: looks like that is already done
https://github.com/specify/specify7/blob/207df9a091c59cd04e4e4b1c3eb111c75c74f68a/specifyweb/frontend/js_src/lib/components/FormMeta/MergeRecord.tsx#L61-L66

the reason it doesn't work is that those extra filters were only respected by regular search, not query builder search until xml-editor branch (this branch likely doesn't have the fix)

thus the issue would likely fix itself in 7.10

if not, just call deduplicate selected resources once selected and abort if there is only one

2023-07-27 13:05 UTC, merged

2023-09-12 16:32 UTC, realVinayak commented
The actual fix would be on the backend - it is integrity error if trying to merge into self.