Don't clone fields unique to database
specify/specify7 pull request #3963
Opened 2023-09-01 14:10 UTC by melton-jason

Fixes #3960 

The following fields should not be carried over/cloned: 
> * Collectingevent uniqueIdentifier
> * CollectionObject uniqueIdentifier
> * Institution name
> * Locality uniqueIdentifier
> * Permit permitNumber
> * SpAppResourceData spAppResource
> * Specifyuser name

(Also, there was another issue in which global uniqueness rules were not working on the frontend. That fix should be included in #3962)

2023-09-02 03:27 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/DataModel/resource.ts
> +          uniquenessRules === undefined
(I seen https://github.com/specify/specify7/issues/3960#issuecomment-1702819456)

can you double-check that this doesn't mark absolutely every field as unique, and rather only fields that have uniqueness constraints of some sort?

also, if you have a moment to spare, can you update/add the test cases?

2023-09-06 16:59 UTC, CarolineDenis approved these changes

2023-09-06 20:19 UTC, grantfitzsimmons requested changes
When cloning accessions, I still get this error when there is an existing agent:
https://github.com/specify/specify7/issues/3967

Is this in the scope of this PR?

2023-09-06 21:21 UTC, melton-jason commented
> When cloning accessions, I still get this error when there is an existing agent: #3967
> 
> Is this in the scope of this PR?

That issue (#3967) has been around since at _least_ `v7.8.10` (and possibly earlier, I just stopped checking previous versions).
I do not think there is enough overlap in underlying cause to justify that solution being included in this PR. 

_However_, it still could be included in the `v7.9` release in it's own PR if it is important enough (at the cost of further delaying the release)

2023-09-06 21:38 UTC, grantfitzsimmons approved these changes

2023-09-06 21:39 UTC, grantfitzsimmons commented
> I do not think there is enough overlap in underlying cause to justify that solution being included in this PR.

I agree. Let's fix at a later time.

2023-09-07 13:31 UTC, realVinayak approved these changes

2023-09-07 13:49 UTC, merged