Add warning dialog when no prep available in disposal
specify/specify7 pull request #4030
Opened 2023-09-20 21:02 UTC by CarolineDenis

Fixes #3297

2023-09-20 23:42 UTC, maxxxxxdlp approved these changes
code looks good, but given that interactios code is tricky, buggy, legacy, and doesn't contain tests, I would encourage someone to test the InteractionDialog in all scenarios where it's used after this change

2023-09-27 20:48 UTC, bronwyncombs requested changes
Same situation as Loans/Gifts

https://github.com/specify/specify7/pull/3936#pullrequestreview-1647439386

2023-09-28 16:31 UTC, CarolineDenis commented
@carlosmbe @bronwyncombs 
Expected behavior: 
- If cat # entered with no prep: warning message below the entry box 'This cat # has no prep' + possibility to continue without prep OR to update it
- If cat # entered with prep: goes to new dialog with prep available / unavailable table 
- If cat # entered with prep and cat # without entered: warning message below the entry box 'This cat # has no prep' for the concerned cat # + possibility to continue => continue will bring to the new dialog with prep available / unavailable table with only the cat # containing preps

2023-09-28 20:44 UTC, carlosmbe approved these changes
Tested Disposal Preps and Loans. 

Passed the following:

If cat # entered with no prep: warning message below the entry box 'This cat # has no prep' + possibility to continue without prep OR to update it
If cat # entered with prep: goes to new dialog with prep available / unavailable table
If cat # entered with prep and cat # without entered: warning message below the entry box 'This cat # has no prep' for the concerned cat # + possibility to continue => continue will bring to the new dialog with prep available / unavailable table with only the cat # containing preps

2023-09-28 21:58 UTC, merged