Fix specifyuser not being taken as main agent
specify/specify7 pull request #4033
Opened 2023-09-21 12:57 UTC by realVinayak

>       Array.from(rawSpecifyResources).sort(
>         multiSortFunction(
>           (resource) => resource.get('specifyUser') ?? '',
>           true,
>           (resource) => resource.get('timestampCreated')
>         )
>       )

The problem in above code is that `null < 'aaa'`  returns false.

2023-09-21 13:05 UTC, realVinayak commented
To test:
1. Find two agents such that one agent was created before, but doesn't have a specify user. And the second agent was created after, but has a specify user. An example of this is `Martin Pullan` in herb-rbge

2023-09-22 00:32 UTC, maxxxxxdlp approved these changes

2023-09-22 00:36 UTC, maxxxxxdlp requested changes
It works correctly it seems:

```js
[null,'a'].sort(multiSortFunction((x)=>x,true))
// ["a", null]
```

the resource that has an agent should come first. if all resources don't have agents, oldest resource should come first (which is the resource with lowest value of timestampCreated)

2023-09-22 00:36 UTC, maxxxxxdlp commented
I mean, this PR doesn't break it, but I don't think it was broken before either

2023-09-22 00:37 UTC, maxxxxxdlp commented
I would advise to extract that logic into a function and add tests for that function

2023-09-22 00:48 UTC, maxxxxxdlp approved these changes
ups, saw your Slack message.

I see now, it doesn't always work correctly:
```
[null,'a',null].sort(multiSortFunction((x)=>x,true))
// [null,'a',null]
```

2023-09-22 17:09 UTC, merged