Account for Collection Prefs when cloning/carry forwarding
specify/specify7 pull request #4160
Opened 2023-10-25 14:22 UTC by melton-jason

Fixes #3278 

TO TEST:
- Ensure the `CO_CREATE_PREP_<COLLECTION>` preference is defined in Remote Preferences
  - Replace `<COLLECTION>` with the id of the collection you are testing this in
- Clone and Carry Forward a CollectionObject which has existing preparations. 
- Clone and Carry Forward a CollectionObject which does not have preparations

- Test the other "collection preferences" related to automatic resource creation/initialization which can be defined in Remote Preferences:
  - CO_CREATE_COA_<COLLECTION> (Collection Object Attribute)
  - CO_CREATE_DET_<COLLECTION> (Determination)

2023-10-26 14:23 UTC, CarolineDenis approved these changes

2023-11-08 15:24 UTC, melton-jason commented on specifyweb/frontend/js_src/lib/components/DataModel/__tests__/domain.test.ts
> +    ).resolves.toBe(1);
Can you further explain what you mean by this? 
When the preference (for this example, I will use the CO_CREATE_PREP) is enabled for the currently logged in collection, there are two cases to consider when initializing a CollectionObject. 

Either: 
- The CollectionObject does not have any preparations
  - In which case create a new one
- The CO  already has preparations
  - In which case there should be no new preparations 

Both of these cases are handled by these tests. 
Do you mean test when the preference is not configured?

2023-11-08 17:03 UTC, realVinayak requested changes

2023-11-08 17:03 UTC, realVinayak commented on specifyweb/frontend/js_src/lib/components/DataModel/__tests__/domain.test.ts
> +    ).resolves.toBe(1);
> Both of these cases are handled by these tests.
They aren't? Doesn't this test check if cloned collection object has preparations? Maybe I don't have have context. Can you quote the line where you are checking that cloned collection object does not have preparations?

2023-11-08 18:09 UTC, melton-jason commented on specifyweb/frontend/js_src/lib/components/DataModel/__tests__/domain.test.ts
> +    ).resolves.toBe(1);
> - The CollectionObject does not have any preparations
>   - In which case create a new one

https://github.com/specify/specify7/blob/a09ecc062ed1f6f7513a6bb194974214bd54ee37/specifyweb/frontend/js_src/lib/components/DataModel/__tests__/domain.test.ts#L121-L126

- - - 

> - The CO  already has preparations
>   - In which case there should be no new preparations 

We add a preparation to the CollectionObject here: 

https://github.com/specify/specify7/blob/a09ecc062ed1f6f7513a6bb194974214bd54ee37/specifyweb/frontend/js_src/lib/components/DataModel/__tests__/domain.test.ts#L141-L150

After cloning, the CollectionObject still only has one preparation:

https://github.com/specify/specify7/blob/a09ecc062ed1f6f7513a6bb194974214bd54ee37/specifyweb/frontend/js_src/lib/components/DataModel/__tests__/domain.test.ts#L158-L162

Previously, for this case the cloned CollectionObject would have two or three preparations; the preparation that had existed before, as well as an empty preparation which was created when the resource was initialized (hence the issue). 

> Can you quote the line where you are checking that cloned collection object does not have preparations?
In this case, the cloned CollectionObject _should_ have preparations: the preparation which existed on the original, pre-cloned CollectionObject. 

If the preference is set, there is no case in which a cloned CollectionObject should have no preparations, right?

2023-11-09 16:24 UTC, pashiav approved these changes
I tested for both the Clone and Carry Forward features and they both do what is expected of them! No incorrect duplicates. Adding new determinations also works. Looks good!
**Collection object with No Preparations:** 
![issue-3278-no prep](https://github.com/specify/specify7/assets/118556884/5852e4d3-af6d-4161-9158-2f68dfc06af1)
**Collection object with Existing Preparations:**
![issue-3278-prep](https://github.com/specify/specify7/assets/118556884/77930779-9bb4-4533-8a85-ea699c17bea7)

Added lines in remote pref:
![Screen Shot 2023-11-09 at 10 23 08 AM](https://github.com/specify/specify7/assets/118556884/9c4ce314-ae31-4367-9885-8e78cd0040df)

2023-11-13 18:06 UTC, merged

2023-12-19 14:23 UTC, specifysoftware commented
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-9-2-release-announcement/1452/1