Add view setName to category when not a collection
specify/specify7 pull request #4183
Opened 2023-11-01 18:28 UTC by CarolineDenis

Fixes #4176

2023-11-01 19:21 UTC, CarolineDenis commented
Before
![Screenshot 2023-11-01 at 12 20 31 PM](https://github.com/specify/specify7/assets/108160931/cb5d1b57-7a7a-4c7a-9b6f-73741e1e5a4d)

After
![Screenshot 2023-11-01 at 12 20 21 PM](https://github.com/specify/specify7/assets/108160931/ff4723de-aaa5-4825-b210-937abf74a203)

2023-11-02 03:13 UTC, maxxxxxdlp approved these changes

2023-11-02 03:13 UTC, maxxxxxdlp commented on specifyweb/frontend/js_src/lib/components/FormEditor/fetchAllViews.ts
> +      : undefined) ?? camelToHuman(`${view.viewsetLevel} ${view.viewsetName}`),
(optional) could we put some punctuation between level and name?

i.e
`${view.viewsetLevel} > ${view.viewsetName}`
or the nicer
`${view.viewsetName} (${view.viewsetLevel})`

2023-11-02 14:47 UTC, grantfitzsimmons requested changes
![image](https://github.com/specify/specify7/assets/37256050/8edd5292-38f5-4fe3-9283-fb6537e40075)

Instead of "Discipline Fish Views", can we make it accurate to the discipline the form definition comes from? 

In this case, it should say "Ichthyology Discipline" where `Ichthyology` comes from the `discipline.Name` field so that it is based on the actual name assigned by the user. 

Some people use "Botany" as the discipline template but manage pathogens or lichens in it instead. This would make the name more intuitive for users.

2023-11-02 15:18 UTC, CarolineDenis commented
DECISION: 
Only display "Herpetology View" and loose Discipline.

2023-11-02 17:33 UTC, grantfitzsimmons approved these changes
💯 🚀

2023-11-03 01:29 UTC, maxxxxxdlp commented
before merging this, @CarolineDenis can you test how dropping the viewsetLevel affect view sets from other levels?
if you are not sure, then proceed to only drop viewsetLevel when viewsetLevel is discipline

2023-11-03 13:48 UTC, CarolineDenis commented
@maxxxxxdlp , @grantfitzsimmons , note that the discipline has been added as a title of the list in https://github.com/specify/specify7/pull/4190

2023-11-13 15:06 UTC, pashiav approved these changes
Looks good!
![issue-4176](https://github.com/specify/specify7/assets/118556884/1f62abfd-2c1b-43fc-9edd-95c1e1a9767c)

2023-11-13 15:47 UTC, merged