Remove undefined value from records to prevent attachment loading
specify/specify7 pull request #4252
Opened 2023-12-04 17:03 UTC by CarolineDenis

Fixes #4247

2023-12-05 05:56 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/Attachments/RecordSetAttachment.tsx
> +        .filter((record) => record !== undefined)
use filterArray

2023-12-05 05:57 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/Attachments/RecordSetAttachment.tsx
> +        .findIndex((record) => record?.populated !== true);
don't need `?` anymore here

2023-12-05 05:58 UTC, maxpatiiuk requested changes
see https://github.com/specify/specify7/pull/4252/files#r1414916180

2023-12-06 04:47 UTC, maxpatiiuk approved these changes

2023-12-06 15:30 UTC, bronwyncombs approved these changes
Looking good! No more skeleton loading in attachment viewer :-)

Record Set with attachments: 
<img width="1689" alt="Screenshot 2023-12-06 at 9 17 54 AM" src="https://github.com/specify/specify7/assets/135047322/905ed3af-8fbb-4ca8-9dd2-1ed6972bc8a4">
Record Set without attachments:
<img width="1689" alt="Screenshot 2023-12-06 at 9 18 29 AM" src="https://github.com/specify/specify7/assets/135047322/d66be75f-f776-4083-9f32-d816a5dba298">

Browse in Forms records w/ attachments:
<img width="1689" alt="Screenshot 2023-12-06 at 9 26 23 AM" src="https://github.com/specify/specify7/assets/135047322/c0bb9130-efd0-426b-bbbe-6e824748d775">

Browse in Forms records w/o attachments:

<img width="1689" alt="Screenshot 2023-12-06 at 9 27 46 AM" src="https://github.com/specify/specify7/assets/135047322/dd8f380b-ceee-4f26-8ebf-3e0cfcaee6b9">

https://github.com/specify/specify7/assets/135047322/3ab4eadd-92d4-4f3c-b934-ed0d10a9c686

2023-12-06 16:36 UTC, merged