Define proper user type for global resource
specify/specify7 pull request #4282
Opened 2023-12-11 22:37 UTC by CarolineDenis

Fixes #3956

2023-12-11 22:39 UTC, CarolineDenis commented
NOTES: 
- don't forget to uncomment spAppResourceDir in webOnlyViews 
- add a way to only choose from Preferences or Global Preferences when "Other Properties Resource" is chosen?

2023-12-12 21:48 UTC, CarolineDenis commented
@maxpatiiuk , 
Can we create two new keys one for Preferences and one for Global Preferences that would have a name? We would then use those to create them instead of otherPropertiesResource. 
https://github.com/specify/specify7/blob/84e56043528e3fa4c765d31da0f186882de86116/specifyweb/frontend/js_src/lib/components/AppResources/types.tsx#L199

2023-12-13 04:29 UTC, maxpatiiuk requested changes

2023-12-13 04:29 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/AppResources/tree.ts
> +  if (globalDirectories.length < directoriesNeeded.length) {
this condition should be removed - this assumes that there are only 3 possible user types at a global level - not an assumption I am willing to make given that these directories are created by sp6 - who knows what it does

2023-12-13 04:29 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/AppResources/tree.ts
> +    );
this code assumes that at most 1 user type is missing - can you rewrite to add any user type that is missing, not just one?

2023-12-13 04:29 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/AppResources/types.tsx
> +  },
we are not encouraging users to create these app resources (they should be created by sp6 in every database). In fact, we should deprecate these app resources as soon as Institutional Preferences are added), thus we should not be exposing explicit options for these legacy resources in the UI.

2023-12-13 04:30 UTC, maxpatiiuk commented
see also https://github.com/specify/specify7/issues/3956#issuecomment-1853251752 for proposed solutions

2024-01-02 18:36 UTC, closed without merging