Add name field to view set when missing
specify/specify7 pull request #4388
Opened 2024-01-10 21:51 UTC by CarolineDenis

Fixes #4366

Work in progress

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [ ] Add relevant issue to release milestone

### Testing instructions

2024-01-11 23:44 UTC, maxpatiiuk requested changes

2024-01-11 23:44 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/FormEditor/Create.tsx
> +  const newName = appResource.get('name');
rename this variable to `appResourceName` or something like that - so that it's not confused with view name

2024-01-11 23:44 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/FormEditor/Create.tsx
> +            ),
why pass the name to createViewDefinition and have it pass it right back when you can just use it here right away?

```suggestion
            {
              ...createViewDefinition(viewSets, uniqueName, table, template),
              name: viewSets.name === '' ? appResource.get('name') : viewSets.name,
            }

2024-01-11 23:44 UTC, maxpatiiuk commented
> I ended up adding the new name to the view set in both createNewView() and createViewFromTemplate(). Which I tested.
I would have liked to implement this in the Editor component like you suggested but couldn't find a way for it to behave like expected. Is this fine with you or do you have suggestions?

2024-01-12 18:07 UTC, emenslin approved these changes
Looks good, can now see the name in the view set. 
Before 
<img width="532" alt="Screenshot 2024-01-12 113525" src="https://github.com/specify/specify7/assets/150940840/be9c37b0-1deb-4596-9277-8bf68f69ed05">
After 
<img width="552" alt="Screenshot 2024-01-12 113515" src="https://github.com/specify/specify7/assets/150940840/947365cf-079a-47a7-b230-8d80b8e2d63e">

2024-01-12 18:09 UTC, pashiav approved these changes
Looks good! Name in view set appears in all cases.

![Screen Shot 2024-01-12 at 12 04 49 PM](https://github.com/specify/specify7/assets/118556884/c16801b3-b4f2-41ad-8930-5f3a82b4cfb3)
![Screen Shot 2024-01-12 at 12 05 44 PM](https://github.com/specify/specify7/assets/118556884/54caf9fb-7130-4773-9563-8b3782094fed)

2024-01-12 23:06 UTC, maxpatiiuk approved these changes

2024-01-16 16:09 UTC, merged