Fix spelling mistake in leaving dialog
specify/specify7 pull request #4460
Opened 2024-01-24 19:03 UTC by CarolineDenis

Fixes #4453

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

Go to schema config>uniqueness rules
add uniqueness rule
click close without saving
See correct spelling of 'Unsaved changes would be lost if you leave this page.'

2024-01-24 21:01 UTC, pashiav approved these changes
Looks good!
![issue-4453](https://github.com/specify/specify7/assets/118556884/db1d2040-2ed3-4286-a118-0a63d66e5b54)

2024-01-25 01:22 UTC, grantfitzsimmons approved these changes

2024-01-25 03:55 UTC, maxpatiiuk requested changes

2024-01-25 03:55 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/localization/main.ts
> -    'en-us': 'Unsaved changes would be lost if your leave this page.',
why where the other languages removed?
(the translations looked a good)

also, when en string changes, weblate automatically flags other strings for manual review (and shows to translators how the en string changes, so you certainly don't need to remove the strings in the code

---

and, the original issue mentioned:

> also maybe "would" should be "will"?

is that something we should change?

@grantfitzsimmons

2024-01-26 01:51 UTC, maxpatiiuk approved these changes

2024-01-26 14:27 UTC, merged