Enable formatted for a field format when available
specify/specify7 pull request #4469
Opened 2024-01-26 19:24 UTC by CarolineDenis

Fixes #4466

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

Go to schema config
Select loan table
Select loanNumber
Try to select a field format -> 'Formatted'

2024-01-27 00:52 UTC, maxpatiiuk approved these changes

2024-02-12 17:03 UTC, pashiav requested changes
Does not allow selection.

https://github.com/specify/specify7/assets/118556884/3adc7db1-c06e-4985-a96f-976f8254ee01

2024-02-12 20:12 UTC, pashiav approved these changes
Looks good! Can select and save without issue.

2024-02-13 17:21 UTC, emenslin approved these changes
Looks good, can now select formatted field and it works as expected.

2024-02-13 17:39 UTC, merged