Allow dialog to reduce size once skeleton disappears in att gallery
specify/specify7 pull request #4571
Opened 2024-02-21 16:11 UTC by CarolineDenis

Fixes #4549

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

Go to a record set without any attachments
Click on attachment gallery
See the skeleton
See the skeleton disappear 
See the dialog shrinks

2024-02-21 23:28 UTC, maxpatiiuk requested changes

2024-02-21 23:28 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/Attachments/RecordSetAttachment.tsx
> +            fetchedCount.current === records.length ? undefined : false
what is `fetchedCount.current === records.length` supposed to represent
all attachments loaded?
some attachments loaded?

edit: looks like it means "isComplete". could you please extract this into a variable called `isComplete` and use it here, and also on line 144?
that would improve code clarity

2024-02-22 17:33 UTC, emenslin approved these changes
Looks good, dialog appearing as expected. 

https://github.com/specify/specify7/assets/150940840/995c1ce9-2fee-4298-a0db-0a9d529f7a00

2024-02-22 21:21 UTC, pashiav approved these changes
Looks good!
<img width="1906" alt="Screen Shot 2024-02-22 at 3 21 01 PM" src="https://github.com/specify/specify7/assets/118556884/dbdbab39-f8ed-4b78-9991-cbf54f056adb">

2024-02-23 03:01 UTC, maxpatiiuk approved these changes

2024-02-23 16:40 UTC, merged