feat(FormParse): allow "false" as default value for Boolean
specify/specify7 pull request #4585
Opened 2024-02-24 04:34 UTC by maxpatiiuk

Fixes #4581

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions

1. Add a checkbox to the form with `default="true"`.
2. Open the form
3. Without touching the checkbox, save the resource to the database
4. Run a Query Builder query on the resource and make sure that in the query results, the checkbox field has true value
5. Do the above steps with `default="false"` and make sure that query results has false value
6. Do the above steps with no `default` attribute and make sure that query results cell for this value is empty

2024-02-27 18:24 UTC, melton-jason approved these changes

2024-02-27 21:11 UTC, emenslin requested changes
This does not seem to be working, when I follow the instructions for any of the default values it always shows up as empty in the query.

2024-02-28 04:39 UTC, maxpatiiuk commented
Thanks for catching the issue - looks like there is an additional place that needed to be modified.
Though, this PR now affects a highly important file useResourceValue, and thus I would suggest we don't merge this PR in 7.9.4, but merge it after this release to give more time for general testing

2024-02-29 17:07 UTC, emenslin approved these changes
Looks good, the different default values are now showing up as expected!

2024-02-29 17:17 UTC, merged