Ensure WorkBench always checks for uniqueness rules
specify/specify7 pull request #4593
Opened 2024-02-28 15:14 UTC by melton-jason

Fixes #4500 

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [ ] Add relevant issue to release milestone

### Testing instructions

2024-02-28 15:50 UTC, CarolineDenis approved these changes

2024-02-29 00:32 UTC, maxpatiiuk approved these changes

2024-02-29 14:45 UTC, pashiav requested changes
Still validates with the same example from https://github.com/specify/specify7/issues/4500#issue-2127446816.
![issue-4500](https://github.com/specify/specify7/assets/118556884/9afee84f-dfc6-4f7a-b086-35db5cf1ae1b)

2024-02-29 17:39 UTC, melton-jason commented
> Still validates with the same example from [#4500 (comment)](https://github.com/specify/specify7/issues/4500#issue-2127446816). ![issue-4500](https://private-user-images.githubusercontent.com/118556884/308963879-9afee84f-dfc6-4f7a-b086-35db5cf1ae1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMjExODcsIm5iZiI6MTcwOTIyMDg4NywicGF0aCI6Ii8xMTg1NTY4ODQvMzA4OTYzODc5LTlhZmVlODRmLWRmYzYtNGY3YS1iMDg2LTM1ZGI1Y2YxYWUxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQxNTM0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2EyOTcxMTBmM2Y1YTAyNWNjMmU1ZTk4M2E4OGQyYTczOWUwOWE1YTQ0MmViMWQ1ZDEwNWNmNDc0MTExYmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7rOmzVwlTjSYd7iLyRDXh558XTbI6wxlasJqfdh2YCc)

@pashiav 

The rule states that the First and Last names of the Agent must be unique to the CollTechContac's Discipline. Thus to validate the rule, the Agent records must have the relationship. Uniqueness Rules consider two records as not violating a rule if they do not have a relationship in the scope path. 

<img width="444" alt="Screenshot 2024-02-29 at 11 38 28 AM" src="https://github.com/specify/specify7/assets/64045831/d2f71667-2902-442b-8eef-bf5e5e41f45f">


The below Dataset matches the CollTechContact to the currently logged in collection to demonstrate the rule:

<img width="1436" alt="Screenshot 2024-02-29 at 10 24 12 AM" src="https://github.com/specify/specify7/assets/64045831/c2ff150f-6217-4509-83d2-7e6d04aba84d">

2024-03-01 18:42 UTC, emenslin approved these changes
Looks good, workbench is checking for uniqueness rules. 
<img width="515" alt="Screenshot 2024-03-01 123817" src="https://github.com/specify/specify7/assets/150940840/e3bf73a0-afcb-4af0-9886-a8c8f92bc204">
<img width="812" alt="Screenshot 2024-03-01 124051" src="https://github.com/specify/specify7/assets/150940840/94485f45-f633-4a8e-b8a0-c31802ac84ea">

2024-03-04 15:25 UTC, pashiav approved these changes

2024-03-05 17:15 UTC, merged