Add a way to explicity choose aggregators in QB
specify/specify7 pull request #4646
Opened 2024-03-13 17:04 UTC by CarolineDenis

Fixes #4620

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- Navigate to the Query Builder (QB).
- Select a table that you know has one or several aggregators (To check, go to app resources, navigate to Record Formatter, choose the table, select aggressors tab, and verify the list of aggregators names available).
- Choose "aggregated."

- [ ] Verify that in the query line, after selecting the "aggregated" field box, a drop-down appears with a list of aggregators choices (corresponding to the list in app resources).

 Verify that changing the aggregator changes the way the field is displayed in the results table.

2024-03-15 18:56 UTC, acwhite211 commented
The problem seems to be that the back-end is ignoring the formatter name in the request.  It is just getting the aggragator and then getting the formatter that the aggregator is pointing to.  I changed the code so that it takes into account the 'formatter name' that is passed in the query builder request.  I just need to fix some of the unit tests now.

2024-03-17 03:27 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/QueryBuilder/Line.tsx
> +          isFormatted && mappingPath.at(-1) === '#1'
could you please apply the fixes I mentioned in https://github.com/specify/specify7/pull/4615#pullrequestreview-1932351672 in here?

2024-03-19 02:13 UTC, maxpatiiuk approved these changes

2024-05-06 20:45 UTC, emenslin requested changes
### Testing instructions

- Navigate to the Query Builder (QB).
- Select a table that you know has one or several aggregators (To check, go to app resources, navigate to Record Formatter, choose the table, select aggressors tab, and verify the list of aggregators names available).
- Choose "aggregated."

- [x] Verify that in the query line, after selecting the "aggregated" field box, a drop-down appears with a list of aggregators choices (corresponding to the list in app resources).

- [ ] Verify that changing the aggregator changes the way the field is displayed in the results table.

Changing the aggregator does not change the way the field is displayed and seems to only show the default aggregation. 

https://github.com/specify/specify7/assets/150940840/3a54fd5f-36dd-4135-a86b-b139a304493f

2024-05-08 16:57 UTC, emenslin approved these changes
### Testing instructions

- Navigate to the Query Builder (QB).
- Select a table that you know has one or several aggregators (To check, go to app resources, navigate to Record Formatter, choose the table, select aggregator tab, and verify the list of aggregators names available).
- Choose "aggregated."

- [x] Verify that in the query line, after selecting the "aggregated" field box, a drop-down appears with a list of aggregators choices (corresponding to the list in app resources).
- [x] Verify that changing the aggregator changes the way the field is displayed in the results table.

Looks good, changing the aggregator changes the results now!

https://github.com/specify/specify7/assets/150940840/6c9ba09a-391c-4283-8f09-b19e49809895

2024-05-13 18:18 UTC, alesan99 approved these changes
- [x] Verify that in the query line, after selecting the "aggregated" field box, a drop-down appears with a list of aggregators choices (corresponding to the list in app resources).

Added new aggregators and it looks good, & changes are reflected in Query results

![chrome_8GE0d2wOxq](https://github.com/specify/specify7/assets/8108710/9e60cb1a-6612-44fd-89fb-de90b8a6275b)

2024-05-21 16:43 UTC, merged