Add key to ResourceView to avoid data being carried away
specify/specify7 pull request #4672
Opened 2024-03-20 17:00 UTC by CarolineDenis

Fixes #4670

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- Create a loan
- Either add a record set or add some catalog numbers
- Click the add button next to loan preparations
- Add unassociated item
- [ ] Verify that new prep form is empty

2024-03-20 19:42 UTC, pashiav requested changes
### Testing instructions

- Create a loan
- Either add a record set or add some catalog numbers
- Click the add button next to loan preparations
- Add unassociated item
- [X] Verify that new prep form is empty

--
The form is empty - functionality looks good!

When adding an unassociated item, the form does not automatically display that new item and the user has to click the arrows to navigate to it. This could be confusing to users as they cannot immediately tell if anything was added or changed on the form. 

https://github.com/specify/specify7/assets/118556884/ed78594d-ef40-48bc-810f-18ad577cbfe5

Expected behavior in `v7.3.1`:

https://github.com/specify/specify7/assets/118556884/460c8201-2bcd-45f0-ad8b-1d8e2556fc5f

2024-03-20 20:00 UTC, CarolineDenis commented
@pashiav, 
That's a known behavior that we will fix later on in another issue (having to click the arrow to go to the new record)

2024-03-20 20:33 UTC, pashiav approved these changes

2024-03-21 01:54 UTC, maxpatiiuk approved these changes

2024-03-21 15:58 UTC, emenslin approved these changes
### Testing instructions

- Create a loan
- Either add a record set or add some catalog numbers
- Click the add button next to loan preparations
- Add unassociated item
- [x] Verify that new prep form is empty

Looks good!

2024-03-22 13:43 UTC, merged