Fix dialog resizing issues
specify/specify7 pull request #4675
Opened 2024-03-21 17:07 UTC by CarolineDenis

Fixes #4519

Fixes #4511 

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

Code lost during merge

2024-03-21 17:27 UTC, emenslin approved these changes
- [x] Can now exit out of full screen in GeoMap
- [x] Dialogs now shrink back down in size when things are removed 

https://github.com/specify/specify7/assets/150940840/e98b6b5e-3bd2-4dff-b792-d184fc72c2ef

2024-03-21 23:48 UTC, pashiav reviewed
- [x] Can now exit out of full screen in GeoMap
- [x] Dialogs now shrink back down in size when things are removed

2024-03-21 23:48 UTC, pashiav approved these changes

2024-03-22 00:32 UTC, maxpatiiuk requested changes
Let's merge the original PR (https://github.com/specify/specify7/pull/4535) instead of creating a duplicate PR

2024-03-22 00:32 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/Molecules/Dialog.tsx
> +const freezeSizeAfter = 2 * SECOND;
When the code was copied, not all changes got copied - the original PR fixed the definition of `SECOND` which is not present in this PR

2024-03-22 00:33 UTC, maxpatiiuk commented
> Code lost during merge

Code wasn't lost)
The PR just needs to be merged

As a reminder:
- I had a time-units-simplifications PR for refactoring time units
- The dialog fixes branch was based on it since it relied on the changes in that PR.
- Dialog fixes branch is merged (into time-units-simplifications)
- time-units-simplifications should be merged too to get the fixes into production

2024-03-22 13:24 UTC, CarolineDenis commented
Fixed in https://github.com/specify/specify7/pull/4535

2024-03-22 13:24 UTC, closed without merging