Display header in grid table for first collapsed row
specify/specify7 pull request #4694
Opened 2024-03-27 20:55 UTC by CarolineDenis

Fixes #4692

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

Go to https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/collectionobject/608836/

- [ ] See there is heading above the record in Preparations

2024-03-28 14:02 UTC, pashiav requested changes
### Testing instructions

Go to https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/collectionobject/608836/

- [X] See there is heading above the record in Preparations
---

Headings appear, looking good!!
![Screen Shot 2024-03-28 at 8 54 46 AM](https://github.com/specify/specify7/assets/118556884/22cdfc8d-abfc-406b-8ba7-f14cb4244763)

---
When a Preparation is expanded, there is a large gap between the heading and the prep. The expected behavior is on the right on branch `edge`, which does not have as wide of a gap.
![Screen Shot 2024-03-28 at 9 01 51 AM](https://github.com/specify/specify7/assets/118556884/d42f40fb-7ddb-4f99-bb2d-675c4c6d1fcc)

2024-03-28 15:23 UTC, CarolineDenis commented
@maxpatiiuk , do we really want to keep the code to avoid the shift? It creates a lot of complications in the UI now

2024-03-28 16:15 UTC, emenslin approved these changes
### Testing instructions

Go to https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/collectionobject/608836/

- [x] See there is heading above the record in Preparations

Looks good!
<img width="804" alt="Screenshot 2024-03-28 111413" src="https://github.com/specify/specify7/assets/150940840/2372a9e3-49fd-4331-8638-7806c82fae4f">

2024-03-28 17:19 UTC, grantfitzsimmons approved these changes
> Go to [fitznhmaoct2023-edge.test.specifysystems.org/specify/view/collectionobject/608836](https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/collectionobject/608836/)
> 
>  - [x] See there is heading above the record in Preparations

Funny that the link is to a deployment on `edge` :joy:
We might want to have more robust testing instructions in other cases, but it works as expected!

2024-03-29 04:48 UTC, maxpatiiuk commented
> The gap with the headers invisible is normal though, it prevents the row to shift up, which prevent the user clicking somewhere else when rapidly deleting a row.

The gap should only be there if there was more than 1 row, and user removed all but the last one.
The gap should definitely not be there when there is more than 1 row - that would be a bug

2024-03-29 04:50 UTC, maxpatiiuk requested changes
sorry if I am being slow, but I don't see what is the issue in https://github.com/specify/specify7/issues/4692#issuecomment-2026640173

And this PR seems to be introducing a bug. See https://github.com/specify/specify7/pull/4694#issuecomment-2026641720

2024-03-29 13:33 UTC, grantfitzsimmons requested changes
> The gap with the headers invisible is normal though, it prevents the row to shift up, which prevent the user clicking somewhere else when rapidly deleting a row. (Fixed in https://github.com/specify/specify7/pull/4546)

As @maxpatiiuk said:
>The gap should only be there if there was more than 1 row, and user removed all but the last one.
>If user didn't remove the rows, the gap shouldn't be there, so there may be a bug with this PR (unless I am misunderstanding)

I believe he's correct

2024-03-29 14:29 UTC, CarolineDenis commented
NOTES: 
Decision: 
- Any time there is more than 1 row collapsed or not display header, if only one row and it's collapsed headers are displayed, if only one row but expanded than no headers

2024-03-29 14:43 UTC, grantfitzsimmons commented
After discussing this in-depth with @CarolineDenis– I felt that ultimately keeping the header at all times is preferable to having a gap _if_ our primary focus is reducing layout shifts.

Essentially, if you are visualizing a subview as a "table"/"grid", the expectation really should be that it is a table. If you want to simply show expanded record primarily, the form should be configured to display as a "form". 

This really begs the related (but too big for this issue) question– are we visualizing a table effectively in Specify 7? Maybe we need to add separators between the rows and columns.

2024-03-29 15:30 UTC, maxpatiiuk approved these changes
I like this behavior and it simplifies things
I think this is the behavior we had in the past in v7.7 until we changed it to remove redundant heading when you have only 1 row that is expanded.

Feel free to close https://github.com/specify/specify7/pull/4701 as unmerged

2024-03-29 15:30 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/FormCells/FormTable.tsx
> +                      tabIndex={undefined}
remove this attribute as undefined is the default

2024-03-29 15:30 UTC, CarolineDenis commented
let me know @grantfitzsimmons , @maxpatiiuk if we're good with this version

2024-03-29 15:47 UTC, grantfitzsimmons approved these changes

2024-03-29 15:57 UTC, merged