Disable close button when unmapped field
specify/specify7 pull request #4757
Opened 2024-04-08 16:35 UTC by CarolineDenis

Fixes #4747

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- Go to record formatters (through app resources or schema config)
- Click on a table
- Click on a formatter
- Add a field
- Do not map it

- [ ] verify you cannot close the window without mapping the field

2024-04-09 00:29 UTC, maxpatiiuk requested changes
this adds a lot of complexity - why not just filter out unmapped fields before saving (either in react, or in the spec - I can help with that if you need)

2024-04-09 00:29 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/Formatters/Definitions.tsx
> +    formatter.definition.fields.map((item) =>
use .some() instead of .map()

2024-04-09 17:13 UTC, emenslin requested changes
### Testing instructions

- Go to record formatters (through app resources or schema config)
- Click on a table
- Click on a formatter
- Add a field
- Do not map it
- Close the record formatter editor overlay 
- You are back to the table list 
- Click save 
- Reopen you record formatter 

- [x] verify that the unmapped fields have been deleted 

Unmapped fields get removed after saving! 
However if you add another table as a field (e.g. division) and don't map it when you save and open it again it maps to 'formatted' instead of getting removed like the others. 

https://github.com/specify/specify7/assets/150940840/6784a2be-e774-4ba8-b135-d591570e84ac

2024-04-09 17:28 UTC, CarolineDenis commented
@grantfitzsimmons, 
What do we think of this? 

> Unmapped fields get removed after saving!
> However if you add another table as a field (e.g. division) and don't map it when you save and open it again it maps to 'formatted' instead of getting removed like the others.

2024-04-10 14:21 UTC, combs-a requested changes
- [ ] verify that the unmapped fields have been deleted 

Looks good! Unmapped fields are also filtered in conditional format.

However, you can add as many blank/invalid definitions as you want to conditional format and save it, which causes infinite load and error messages. (Example of 'invalid definition' would be putting something besides true/false in a true/false field).

Saving the formatter:

https://github.com/specify/specify7/assets/71564869/4db3d167-d1e5-450b-bc58-c48e78bccf43

Querying w/ an invalid formatter:

https://github.com/specify/specify7/assets/71564869/d17280fb-d38f-4f19-91af-9c8f6734cf6f

Crash report:
[Specify 7 Crash Report - 2024-04-10T14 10 35.870Z.txt](https://github.com/specify/specify7/files/14933438/Specify.7.Crash.Report.-.2024-04-10T14.10.35.870Z.txt)

This was all in Firefox w/ Windows 10, on the Herps-PC collection in sdnhm_herps.

2024-04-10 17:16 UTC, CarolineDenis commented
> Querying w/ an invalid formatter:
This is an issue but not related to this PR

2024-04-10 20:21 UTC, combs-a approved these changes

2024-04-11 03:09 UTC, maxpatiiuk approved these changes

2024-04-11 13:52 UTC, merged