Handle case when default formtable requires default view
specify/specify7 pull request #4776
Opened 2024-04-10 23:51 UTC by melton-jason

> Thankfully there is some consistency amongst the table-only views. Notably, every `altview` in the `altviews` of the view points to a view definition which is of type `formtable`. When reading a form definition for a subview on the frontend, if every altview points to a `formtable` viewdef in a view, we can likely fallback to using the `table.view` view for rendering the expanded definition of the subview (the collapsed view can still remain the original view).

Alternative implementation of #4760 which follows the above proposed solution from https://github.com/specify/specify7/pull/4760#issuecomment-2046022176

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [ ] Add relevant issue to release milestone

### Testing instructions

2024-04-11 00:29 UTC, melton-jason reviewed
The relevant code changes which implement the solution are in the following: 

https://github.com/specify/specify7/blob/ec955a70403e3f482276273dc97c1d4864e046af/specifyweb/frontend/js_src/lib/components/FormParse/index.ts#L183-L188

I am not a fan of making the function asynchronous just for handling this case, although we need the ViewDefinition of the default table view (which is different than the view we are attempting to parse) to correctly resolve the expanded view definition. 

If it's a better solution, I have also considered extracting some form parsing logic from `resolveViewDefinition` to `fetchView` so that the correct view can be recursively fetched and altering the `ViewDefinition` type by adding an attribute for the expanded view definition for this case. 
Then, `resolveViewDefinition` can simply return the correctly resolved expanded view when the frontend wants to access the view with the `form` FormType.

2024-04-11 03:04 UTC, maxpatiiuk approved these changes
sad to see more complications being added to an already complex functions, but this seems like the best way forward

could you also please add tests for this new logic (i.e could add new tests for resolveViewDefinition, or extract the useDefaultExpanded computation logic into a pure function and test that using unit tests)

2024-04-11 03:04 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/FormParse/index.ts
> +      .attributes.type as Lowercase<FormType>) === 'formtable';
given that you only access attributes, you don't need toSimpleXmlNode here

you can also use getAttribute:

```suggestion
    getAttribute(xmlToJson(viewDefinitions[view.altviews[0].viewdef],'type') === 'formtable';
```

2024-04-11 03:04 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/FormParse/index.ts
> +        viewDefinition === undefined
if this is undefined, then maybe we want to just let the function go along with it's default behavior?

```tsx
  if (useDefaultExpanded) {
    const viewDefiniton = await fetchView(strictGetTable(parseJavaClassName(view.class)).view);
    if(typeof viewDefinition === 'object')
      return resolveViewDefinition(viewDefinition, formType, mode)
  }
```

2024-04-11 15:46 UTC, melton-jason commented
> If it's a better solution, I have also considered extracting some form parsing logic from `resolveViewDefinition` to `fetchView` so that the correct view can be recursively fetched and altering the `ViewDefinition` type by adding an attribute for the expanded view definition for this case. Then, `resolveViewDefinition` can simply return the correctly resolved expanded view when the frontend wants to access the view with the `form` FormType.

I have gone ahead and implemented a (hopefully) cleaner solution generally following the above proposal which is less bug prone. 
Now when fetching the view from the backend, if we are fetching one of the table-only views, we fetch the default view for the table and add the non-formtable altviews and viewdefs to the table-only view. 
When the frontend attempts to access the 'expanded' form definition for the altered view, it can then correctly resolve the expanded view definition. 

Essentially, we are making every view follow the pattern of other views (like the default `Preparation` view in https://github.com/specify/specify7/pull/4760#issuecomment-2046022176)

2024-04-11 17:50 UTC, emenslin approved these changes
### Testing instructions
- In the instance, make sure there are no custom views defined for Collectors
- On the view definition for the CollectingEvent, make sure the `collectors` relationship is using the `Collectors` view (ignore this step if using the default): 
```xml
<cell type="subview" viewname="Collectors" id="collect" name="collectors" colspan="13" defaulttype="table" rows="3"/>
```
- Ensure the Collector subview correctly renders the default `Collector` view (pictured below) when the Subview is: 
  - [x] In Subform Mode
  - [x] In Grid Mode and the cell is expanded
  - [ ] Also ensure the correct collapsed view is shown when the Subview is in Grid Mode and the cell is collapsed
- On the CollectingEvent form definition, modify the viewname for the `collectors` relationship to be `Collector`
  - [x] Ensure the collapsed view when the Subview is in Grid Mode is using the `Collector` view definition

- [ ] On the default Agent form, ensure the GroupPerson/Members subview appears as it did in `v7.9+`

Group person subform opens as right aligned and in grid mode it originally opens as collapsed and read only and it should open expanded. 

https://github.com/specify/specify7/assets/150940840/333e6ab8-8ceb-4042-943c-f414e4eadc73

2024-04-11 17:52 UTC, emenslin requested changes
### Testing instructions
- In the instance, make sure there are no custom views defined for Collectors
- On the view definition for the CollectingEvent, make sure the `collectors` relationship is using the `Collectors` view (ignore this step if using the default): 
```xml
<cell type="subview" viewname="Collectors" id="collect" name="collectors" colspan="13" defaulttype="table" rows="3"/>
```
- Ensure the Collector subview correctly renders the default `Collector` view (pictured below) when the Subview is: 
  - [x] In Subform Mode
  - [x] In Grid Mode and the cell is expanded
  - [ ] Also ensure the correct collapsed view is shown when the Subview is in Grid Mode and the cell is collapsed
- On the CollectingEvent form definition, modify the viewname for the `collectors` relationship to be `Collector`
  - [x] Ensure the collapsed view when the Subview is in Grid Mode is using the `Collector` view definition

- [ ] On the default Agent form, ensure the GroupPerson/Members subview appears as it did in `v7.9+`

Group person subform opens as right aligned and in grid mode it originally opens as collapsed and read only and it should open expanded. 

https://github.com/specify/specify7/assets/150940840/333e6ab8-8ceb-4042-943c-f414e4eadc73

2024-04-12 00:57 UTC, maxpatiiuk approved these changes
indeed, much cleaner!

please also add tests if possible as this is critical code

2024-04-12 00:57 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/FormParse/index.ts
> +    return fetchView(strictGetTable(view.class).view).then(
(optional) use await here?

2024-04-12 13:36 UTC, CarolineDenis approved these changes

2024-04-12 15:51 UTC, combs-a approved these changes
### Testing instructions
- In the instance, make sure there are no custom views defined for Collectors
- On the view definition for the CollectingEvent, make sure the `collectors` relationship is using the `Collectors` view (ignore this step if using the default): 
```xml
<cell type="subview" viewname="Collectors" id="collect" name="collectors" colspan="13" defaulttype="table" rows="3"/>
```
- Ensure the Collector subview correctly renders the default `Collector` view (pictured below) when the Subview is: 
  - [X] In Subform Mode
  - [X] In Grid Mode and the cell is expanded
  - [X] Also ensure the correct collapsed view is shown when the Subview is in Grid Mode and the cell is collapsed
- On the CollectingEvent form definition, modify the viewname for the `collectors` relationship to be `Collector`
  - [X] Ensure the collapsed view when the Subview is in Grid Mode is using the `Collector` view definition

- [X] On the default Agent form, ensure the GroupPerson/Members subview appears as it did in `v7.9+`

Looks good, great job!

2024-04-12 18:35 UTC, melton-jason commented
> Group person subform opens as right aligned and in grid mode it originally opens as collapsed and read only and it should open expanded.
> 
>  MU98jDWXJY.mp4

The right-aligned problem is not caused by this PR. 

Check out the default forms for `GroupPerson`:
https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/config/backstop/global.views.xml#L1095-L1117

Specifically the `columnDef` attribute: 

```xml
            <columnDef>60px,2px,p:g,2px</columnDef>
```

If this columnDef is copied to any other view definition and two labels & fields are added to two rows (like the GroupPerson default form), the same issue occurs. 

---
Any behavior with the rows being collapsed/expanded does not seem exclusive to the Collector/GroupPerson (and other affected views I am assuming). 

The behavior I am observing occurs for all SubViews: 
- If the default type of the SubView is `table`, the record becomes expanded whenever added through the plus button
- If the default type of the SubView is `form`, the all records becomes collapsed when switched to table mode, then all other records added while in table mode become expanded

Is this consistent for other SubViews in `edge` and not in this PR?

2024-04-12 18:51 UTC, emenslin approved these changes
### Testing instructions
- In the instance, make sure there are no custom views defined for Collectors
- On the view definition for the CollectingEvent, make sure the `collectors` relationship is using the `Collectors` view (ignore this step if using the default): 
```xml
<cell type="subview" viewname="Collectors" id="collect" name="collectors" colspan="13" defaulttype="table" rows="3"/>
```
- Ensure the Collector subview correctly renders the default `Collector` view (pictured below) when the Subview is: 
  - [x] In Subform Mode
  - [x] In Grid Mode and the cell is expanded
  - [x] Also ensure the correct collapsed view is shown when the Subview is in Grid Mode and the cell is collapsed
- On the CollectingEvent form definition, modify the viewname for the `collectors` relationship to be `Collector`
  - [x] Ensure the collapsed view when the Subview is in Grid Mode is using the `Collector` view definition

- [x] On the default Agent form, ensure the GroupPerson/Members subview appears as it did in `v7.9+`

Looks good!

2024-04-12 20:10 UTC, merged