Filter out empty conditional format def
specify/specify7 pull request #4782
Opened 2024-04-12 14:21 UTC by CarolineDenis

Fixes #4774

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- Go to App Resources -> Record Formatters -> Any table
- Check 'Conditional Format'
- Add a blank field or invalid value 
- Close and save
- Try to query with formatted 
- [ ]Verify you can query and when opening back the record formatter the empty fields are gone

2024-04-12 15:28 UTC, combs-a requested changes
### Testing instructions

- Go to App Resources -> Record Formatters -> Any table
- Check 'Conditional Format'
- Add a blank field or invalid value 
- Close and save
- Try to query with formatted 
- [X] Verify you can query and when opening back the record formatter the empty fields are gone 

Worked well for me--completely blank definitions were removed as well as definitions that had no fields added. It did not remove blank or invalid definitions that had a field (see below for clarity) but these were still ignored in queries.

![image](https://github.com/specify/specify7/assets/71564869/c22e672c-d6c8-4fe4-9b6d-a15de27693b5)

It'd be good to remove the blank definitions regardless of whether or not they have fields, just to make sure everything's cleaned up, but not completely necessary since it doesn't affect queries (from what I can tell).

On a separate note, having some kind of notification/warning to tell the user that there's an invalid conditional format definition so they can go in and fix/remove an invalid, non-blank field would be great, if possible!

Either way, good work! This works great as-is.

2024-04-12 15:48 UTC, emenslin approved these changes
### Testing instructions

- Go to App Resources -> Record Formatters -> Any table
- Check 'Conditional Format'
- Add a blank field or invalid value 
- Close and save
- Try to query with formatted 
- [x]Verify you can query and when opening back the record formatter the empty fields are gone 

Everything seems to be working, no longer an error when querrying.

2024-04-12 18:37 UTC, grantfitzsimmons commented
We need to change the text from:

> This format will be used only if the condition field value equals this condition or if no other format matches it.

to

> This format will be used only if the condition field value equals this condition and cannot be null.

2024-04-12 19:10 UTC, grantfitzsimmons commented
I think we _should_ preserve the ability to have a blank definition in cases where you want no value to be returned when the field meets a specific condition. Because the issue reported by @combs-a is causing errors, I am comfortable removing that capability for now. However, it seems like a feature that would be desirable to retain if it were to function correctly.

2024-04-12 19:11 UTC, grantfitzsimmons commented
> Worked well for me--completely blank definitions were removed as well as definitions that had no fields added. It did not remove blank or invalid definitions that had a field (see below for clarity) but these were still ignored in queries.
> 
> ![image](https://private-user-images.githubusercontent.com/71564869/322031789-c22e672c-d6c8-4fe4-9b6d-a15de27693b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NDkxNjksIm5iZiI6MTcxMjk0ODg2OSwicGF0aCI6Ii83MTU2NDg2OS8zMjIwMzE3ODktYzIyZTY3MmMtZDZjOC00ZmU0LTliNmQtYTE1ZGUyNzY5M2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDE5MDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ZjdlZWRlMjM5ZWI5Y2I3YzA2YTE1N2M4MDJkZmE0MWM5NDUyNmFjYTY1YmIzYzZjNzZhZDFmZjhlZGQxMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nlsLQ42zIcHlIRZyYOyFafhnYYkbqmMUyezoDngSR8M)
> 
> It'd be good to remove the blank definitions regardless of whether or not they have fields, just to make sure everything's cleaned up, but not completely necessary since it doesn't affect queries (from what I can tell).


@combs-a This is acceptable behavior for now as this should be supported in the future:
https://github.com/specify/specify7/issues/4787 

For now, the user will just need to set a field and not leave it `null`.

2024-04-12 20:17 UTC, combs-a approved these changes

2024-04-13 15:03 UTC, maxpatiiuk approved these changes

2024-04-15 13:33 UTC, merged

2024-04-15 13:34 UTC, melton-jason commented on specifyweb/frontend/js_src/lib/localization/resources.ts
> +      condition and is not null.
@specify/ux-testing
Would `empty` be better here? 
How clear to the average Specify User is the concept of nullity in this context? 

```suggestion
      condition and is not empty.
```