Disable save button in QCBX overlay in app resources
specify/specify7 pull request #4891
Opened 2024-05-06 16:16 UTC by CarolineDenis

Fixes #4886

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- Go to app resources -> form definition
- Click on any table with a query combo box in the form (e.g. collection object with the accession qcbx)
- In visual editor click the add button for the query combo box
- Fill out some information in the form
- [ ] verify save button is disabled

2024-05-07 00:08 UTC, maxpatiiuk requested changes
take a look at how FormMeta displays different dialog based on whether it's in the form editor or not, and do something similar here, rather than URL parsing

2024-05-07 12:48 UTC, CarolineDenis commented
@maxpatiiuk , 
Not sure what you mean, it is just not returned from useResourceView(). 
How would this apply to the subforms in app resources?

2024-05-08 03:34 UTC, maxpatiiuk requested changes

2024-05-08 03:34 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/Forms/Save.tsx
> +  const isInViewSet = currentUrl.includes('view-set');
```suggestion
  const isInFormEditor = React.useContext(InFormEditorContext);
```

see https://github.com/specify/specify7/blob/71ad206747904a98fac6043116e2c05331f5036c/specifyweb/frontend/js_src/lib/components/FormMeta/index.tsx#L58

2024-05-08 03:35 UTC, maxpatiiuk commented
> Not sure what you mean, it is just not returned from useResourceView().
How would this apply to the subforms in app resources?

I should clarified that I meant look at how that place detects if it's in the form meta and do something similar to detect if you are in the form editor in here rather than URL parsing

see https://github.com/specify/specify7/pull/4891#discussion_r1593340322

2024-05-08 10:26 UTC, CarolineDenis commented on specifyweb/frontend/js_src/lib/components/Forms/Save.tsx
> +  const isInViewSet = currentUrl.includes('view-set');
mhhh okok! Much better

2024-05-08 14:52 UTC, melton-jason approved these changes
Very clean! 

Currently, you can also delete resources through the form editor. 
Is this also something we want to disable?

2024-05-08 15:04 UTC, CarolineDenis commented
> Very clean!
> 
> Currently, you can also delete resources through the form editor. Is this also something we want to disable?

@grantfitzsimmons ?

2024-05-08 15:32 UTC, grantfitzsimmons commented
> > Currently, you can also delete resources through the form editor. Is this also something we want to disable?

@CarolineDenis I think so!

2024-05-08 23:40 UTC, maxpatiiuk approved these changes

2024-05-09 17:02 UTC, melton-jason approved these changes

2024-05-09 19:12 UTC, lexiclevenger commented
Previewing record formatters using existing records also allows the user to edit and save those records, as well as create and delete records using the query combo boxes. Is that also something that should be addressed in this PR?

2024-05-09 19:35 UTC, CarolineDenis commented
@lexiclevenger, 
We can create a new Issue for that

2024-05-13 16:21 UTC, combs-a approved these changes
- [X] verify save button is disabled 
- [X] verify there is no delete button 

![image](https://github.com/specify/specify7/assets/71564869/e4c5a1c8-b8ec-4616-bf26-abe0d257164c)

![image](https://github.com/specify/specify7/assets/71564869/121d4309-a970-414d-b9a7-e4bf4919f1dc)

This looks good, no delete button and save is disabled even when you go through multiple records it seems. Good work!

2024-05-13 17:43 UTC, alesan99 approved these changes
- Go to app resources -> form definition
- Click on any table with a query combo box in the form (e.g. collection object with the accession qcbx)
- In visual editor click the add button for the query combo box
- Fill out some information in the form
- [x] verify save button is disabled 
- [ ] verify there is no delete button 

Can't save or delete as expected!

2024-05-21 16:39 UTC, merged