Add series tool in query builder
specify/specify7 pull request #4952
Opened 2024-05-24 17:09 UTC by CarolineDenis

Fixes #2000 
Fixes #6166 

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- Open the QB with CO table 
- Add catalog num field and some other field 
- [ ] verify series checkbox is present only when Cat num is one of the field 
- Check Series 
- [ ] verify Distinct is read only 
- Uncheck Series 
- [ ] Verify you can check Distinct and that Series become readonly 
- Uncheck Distinct and check Series 
- Run the query 
- [ ] Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together 
- [ ] Verify that the consecutive cat numbers are displayed as a range 

---
Tips: 
- Create a new CO with a determination and a preparation in a db with auto-numbering for cat num 
- Save 
- Use bulk Carry and create 5 identical copies 
- Create another new CO with all the exact same info as the previous one but skip one cat num 
- This will give you some record to test with series 

---
With Series 
![Screenshot 2025-02-03 at 8 50 57 AM](https://github.com/user-attachments/assets/9cc9d5f2-49f2-404a-babd-7b5664c52515)

Without Series
![Screenshot 2025-02-03 at 8 50 49 AM](https://github.com/user-attachments/assets/8be69707-8601-4dc0-992f-a1f5dbeaafb5)

NOTES: 
Sorting the column cat num is not available for series

2024-07-15 18:45 UTC, grantfitzsimmons commented
This is the second component of #4804

2024-08-22 20:01 UTC, realVinayak commented
FYI: backend, after https://github.com/specify/specify7/pull/4929, will support server-side record cloning

2025-02-03 17:29 UTC, sharadsw approved these changes

2025-02-07 15:56 UTC, acwhite211 approved these changes

2025-02-24 14:39 UTC, grantfitzsimmons commented
@specify/ux-testing It would be great if you could use the same database with Specify 6 to make sure the results are consistent between versions. If they are not, we should try and understand what the difference is.

2025-02-26 15:55 UTC, pashiav requested changes
- [X] verify series checkbox is present only when Cat num is one of the field 
- [X] verify Distinct is read only 
- [X] Verify you can check Distinct and that Series become readonly 
- [ ] Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together 
- [X] Verify that the consecutive cat numbers are displayed as a range 
---
Issues
---

**1. Any operator on catalogNumber does not work.**

https://github.com/user-attachments/assets/99eb999a-f18d-44e1-87c8-73e13c290db6


<br>

2. Ordering does not work with Series checked.
**UPDATE: Will not be included in this PR. Written up issue:** https://github.com/specify/specify7/issues/6291

https://github.com/user-attachments/assets/476e8815-a263-4a2b-8e2a-5cbad4e90dc4

<br>

**3. "Error: Returned 328 results, when expected at most 40"**
[Specify 7 Crash Report - 2025-02-26T15_07_29.529Z.txt](https://github.com/user-attachments/files/18987491/Specify.7.Crash.Report.-.2025-02-26T15_07_29.529Z.txt)
<img width="250" alt="Screenshot 2025-02-26 at 9 07 28 AM" src="https://github.com/user-attachments/assets/7faa1f73-7fb8-4054-b409-bc73f1694b22" />

"Error: Returned 143 results, when expected at most 40":
[Specify 7 Crash Report - 2025-02-26T15_20_36.183Z.txt](https://github.com/user-attachments/files/18987943/Specify.7.Crash.Report.-.2025-02-26T15_20_36.183Z.txt)
I reproduced this error with this query: 
<img width="350" alt="Screenshot 2025-02-26 at 9 20 45 AM" src="https://github.com/user-attachments/assets/ad761fc2-3dff-452c-baa7-4c3ae7b31810" />

<br>

**4. - [ ] Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together** 
- Can't really test this on fields from the Tip because of the error from issue 3. 
- Also noticed that the results show up as "Results: (1)" for the query `catalogNumber -> Any` - is this expected?
<img width="350" alt="Screenshot 2025-02-26 at 9 53 26 AM" src="https://github.com/user-attachments/assets/9ee56a3e-ac7e-42da-92ef-2f4c8d63c64c" />

---

Also I tested locally because on the test panel I get this error upon opening the instance:
[Specify 7 Crash Report - 2025-02-26T15_13_30.978Z.txt](https://github.com/user-attachments/files/18987520/Specify.7.Crash.Report.-.2025-02-26T15_13_30.978Z.txt)

<img width="250" alt="Screenshot 2025-02-26 at 9 13 37 AM" src="https://github.com/user-attachments/assets/4e9928dd-e764-4d83-9770-52661942243a" />

2025-02-27 16:50 UTC, acwhite211 commented
Found an error when there are letters in the Catalog Number field.  Right now, the series grouping logic evaluates adjacent Catalog Numbers by converting them to integers, so there is an error when there are letters.  Working on a fix.
<img width="1163" alt="image" src="https://github.com/user-attachments/assets/82dd83fb-547b-46f6-b06a-63ae856fc433" />

2025-02-27 18:27 UTC, acwhite211 commented
I fixed the series logic for alphanumeric cat nums.  I was able to get the sorting of the series ranged cat nums as well 😀

2025-02-28 21:11 UTC, emenslin requested changes
- [x] verify series checkbox is present only when Cat num is one of the field 
- [x] verify Distinct is read only 
- [x] Verify you can check Distinct and that Series become readonly 
- [x] Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together 
- [x] Verify that the consecutive cat numbers are displayed as a range 

---- 

Adding determinations, modified by agent, or age to the query throws an error

https://github.com/user-attachments/assets/2b0271c6-3c3f-4d21-a9cd-d71a50222bc8


[Specify 7 Crash Report - 2025-02-28T20_47_01.573Z.txt](https://github.com/user-attachments/files/19032985/Specify.7.Crash.Report.-.2025-02-28T20_47_01.573Z.txt)


Results showing incorrect count

https://github.com/user-attachments/assets/99051574-1ff8-4149-b94a-514cf2b41228


If you check series and then delete the Cat # from the query and try to query you get an error

https://github.com/user-attachments/assets/72cdb2bd-cc68-479e-a621-2dedae3c7f76

[Specify 7 Crash Report - 2025-02-28T20_45_22.214Z.txt](https://github.com/user-attachments/files/19032976/Specify.7.Crash.Report.-.2025-02-28T20_45_22.214Z.txt)

2025-03-10 19:55 UTC, acwhite211 commented
Regarding the front-end error `Returned 96 results, when expected at most 40`.
The count on the front-end refers to the amount of rows in the query results, but when selecting, rows representing a series of multiple collection objects will select multiple collection objects.  We might want to discus some more on what behavior we want.  In order to not push this to 10.3, may be we should create a new issue regarding the count display for series queries.

2025-03-10 20:02 UTC, CarolineDenis commented
@acwhite211 
Are those 2 issues fixed? (From @emenslin) 
1) Adding determinations, modified by agent, or age to the query throws an error
2) If you check series and then delete the Cat # from the query and try to query you get an error

2025-03-11 04:49 UTC, acwhite211 commented
Made a change tonight, working on a full solution this morning

2025-04-08 15:36 UTC, pashiav requested changes
- [x] verify series checkbox is present only when Cat num is one of the field 
- [x] verify Distinct is read only 
- [x] Verify you can check Distinct and that Series become readonly 
- Uncheck Distinct and check Series 
- [x] Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together 
- [x] Verify that the consecutive cat numbers are displayed as a range 
--- 

**Issues (from previous reviews)**

From https://github.com/specify/specify7/pull/4952#pullrequestreview-264501646:

> **1. Any operator on catalogNumber does not work.**

Operators still do not work on catnum:
<img width="250" alt="Screenshot 2025-04-08 at 10 20 13 AM" src="https://github.com/user-attachments/assets/ea688631-d159-40bd-b6e1-7c463e107532" />



---
From https://github.com/specify/specify7/pull/4952#pullrequestreview-264501646 & https://github.com/specify/specify7/pull/4952#pullrequestreview-26517804907:
✅ Fixed! Cannot reproduce:
- > **3. "Error: Returned 328 results, when expected at most 40"**

- > The results show up as "Results: (1)" for the query `catalogNumber -> Any` 

	& 

	> Results showing incorrect count

- > Adding determinations, modified by agent, or age to the query throws an error
- > If you check series and then delete the Cat # from the query and try to query you get an error



<br>

2025-04-08 17:24 UTC, acwhite211 commented
@pashiav   tried recreating that issue on ojsmnh_2024_10_03_WB and geo_2024_12_05, but didn't have any occurs appear.  Which database did you use?

<img width="1296" alt="image" src="https://github.com/user-attachments/assets/e311b69a-9fec-4e18-ad36-2018d0f2453b" />

2025-04-08 17:30 UTC, acwhite211 commented
@pashiav I tried to recreate the issue on the databases ojsmnh_2024_10_03_WB and geo_2024_12_05, but couldn't get an error to appear.  Which database did you use?


<img width="1297" alt="image" src="https://github.com/user-attachments/assets/13aab1cc-7e20-41ef-be07-c0c97a77feac" />


<img width="1297" alt="image" src="https://github.com/user-attachments/assets/b7fe91fb-a032-4b69-8ba3-4d5918b68591" />

2025-04-09 16:16 UTC, pashiav commented
@acwhite211 I used calvertmarinemuseum_2025_02_06 on local!

Here is the link to the test panel: https://calvertmarinemuseum20250210-issue-2000.test.specifysystems.org/specify/query/32/
<img width="250" alt="Screenshot 2025-04-09 at 11 13 28 AM" src="https://github.com/user-attachments/assets/391ba73c-6f01-41e9-8446-1b465c0f2315" />

2025-04-11 15:23 UTC, acwhite211 commented
Made a fix for filtering on the Catalog Number in  a series query.  Although, we still have the issue of catnums being strings and not numbers, so filtering on inequalities doesn't work exactly as expected, but that a separate issue.

Old:
```sql
SELECT
	group_concat(concat(collectionobject.`CollectionObjectID`, ':', collectionobject.`CatalogNumber`)) AS co_id_catnum_paired_values
FROM
	collectionobject
WHERE
	collectionobject.`CollectionID` = 4;
```

Fixed:
```sql
SELECT
	group_concat(concat(collectionobject.`CollectionObjectID`, ':', collectionobject.`CatalogNumber`)) AS co_id_catnum_paired_values
FROM
	collectionobject
WHERE
	collectionobject.`CollectionID` = 4
	AND collectionobject.`CatalogNumber` > '5000';
```

2025-04-11 17:41 UTC, emenslin requested changes
- [x] verify series checkbox is present only when Cat num is one of the field 
- [x] verify Distinct is read only 
- [x] Verify you can check Distinct and that Series become readonly 
- [ ] Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together 
- [x] Verify that the consecutive cat numbers are displayed as a range 

--- 

Consecutive, non-default catalog numbers don't get grouped together. 

https://github.com/user-attachments/assets/3db116d8-1646-43f3-a4ca-fbf7068e1d5b


Also at one point I got an error that said 'is phantom', I haven't been able to recreate it but I wanted to make note of it just in case.

2025-04-14 14:06 UTC, pashiav requested changes
- [x] verify series checkbox is present only when Cat num is one of the field 
- [x] verify Distinct is read only 
- [x] Verify you can check Distinct and that Series become readonly 
- [ ] Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together 
- [x] Verify that the consecutive cat numbers are displayed as a range 
---
Could reproduce https://github.com/specify/specify7/pull/4952#pullrequestreview-2761107414  on `calvertmarinemuseum`:
> - [ ] Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together 

> Consecutive, non-default catalog numbers don't get grouped together. 

---
From https://github.com/specify/specify7/pull/4952#pullrequestreview-264501646:

> **1. Any operator on catalogNumber does not work.**

Working for the most part - checked on `ciscollections` and it worked but `calvertmarinemuseum`'s results aren't fully correct.

For some reason there's this one record that appears in the query results in even though it's out of range when Series is checked:
Link to CO: https://calvertmarinemuseum20250210-issue-2000.test.specifysystems.org/specify/view/collectionobject/30721/
Link to query: https://calvertmarinemuseum20250210-issue-2000.test.specifysystems.org/specify/query/33/

<img width="500" alt="Screenshot 2025-04-14 at 8 56 39 AM" src="https://github.com/user-attachments/assets/d0646c67-3295-4afd-bd1b-6d574a135366" />

You can also see in the screenshot above that non-default catnum cots show up regardless of operator. What is the expected behavior?
<img width="250" alt="Screenshot 2025-04-14 at 9 03 17 AM" src="https://github.com/user-attachments/assets/a9ad5c16-3d3e-4db5-a96f-a957b54d5543" />

2025-04-14 14:56 UTC, acwhite211 commented
It seems that an issue with grouping can arise with catnums that do not easily parse into the number.  We have to handle each format on a case-by-case basis.  I try to add a few more cases to handle in this PR, but I think we should create future PRs to identify all the common catnum formats that we want to handle.  Maybe, we can make a dynamic way in the future for applying grouping logic to all collection catnums.

2025-04-17 14:54 UTC, emenslin requested changes
- [x] verify series checkbox is present only when Cat num is one of the field 
- [x] verify Distinct is read only 
- [x] Verify you can check Distinct and that Series become readonly 
- [x] Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together 
- [x] Verify that the consecutive cat numbers are displayed as a range 

--- 

Cannot query on CO -> formatted 

Issue branch: 

https://github.com/user-attachments/assets/05751976-1576-4a7b-9e05-5c15fadcfd97


[Specify 7 Crash Report - 2025-04-17T14_47_51.557Z.txt](https://github.com/user-attachments/files/19796494/Specify.7.Crash.Report.-.2025-04-17T14_47_51.557Z.txt)

Production: 

https://github.com/user-attachments/assets/da8b4ebb-0b53-4368-944f-b2d6166ccf12

2025-04-18 15:11 UTC, acwhite211 commented
@emenslin sorry about that, looks like that was a side-effect of the merge conflict fixes.  Should be good now to re-test.  Thanks!

2025-04-18 16:36 UTC, emenslin requested changes
- [x] verify series checkbox is present only when Cat num is one of the field 
- [x] verify Distinct is read only  
- [x] Verify you can check Distinct and that Series become readonly 
- [x] Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together 
- [x] Verify that the consecutive cat numbers are displayed as a range 

--- 

Original formatted CO issue is fixed, however, if you add formatted CO and cat # and check series it throws an error. 


https://github.com/user-attachments/assets/e753786b-6013-4e96-9a96-a8e91afec8c4


[Specify 7 Crash Report - 2025-04-18T16_33_08.856Z.txt](https://github.com/user-attachments/files/19814395/Specify.7.Crash.Report.-.2025-04-18T16_33_08.856Z.txt)

2025-04-18 16:54 UTC, acwhite211 commented
@emenslin Thanks, looks like that error was caused another line the was similar to the previous error.  Pushed a fix.

2025-04-18 20:13 UTC, emenslin requested changes
- [x] verify series checkbox is present only when Cat num is one of the field 
- [x] verify Distinct is read only  
- [x] Verify you can check Distinct and that Series become readonly 
- [x] Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together 
- [x] Verify that the consecutive cat numbers are displayed as a range 

--- 

Results aren't displayed in the correct order with series checked, this seems to relate to having multiple cat # formats but I'm not entirely sure. In the video it starts with no sorting and then I try sorting by descending and it still doesn't fix it. 


https://github.com/user-attachments/assets/986bafc6-62ec-4329-a2bd-35c19cbb90f2

2025-04-21 14:05 UTC, pashiav requested changes
- [X] verify series checkbox is present only when Cat num is one of the field 
- [X] verify Distinct is read only 
- [X] Verify you can check Distinct and that Series become readonly 
- [X] Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together 
- [X] Verify that the consecutive cat numbers are displayed as a range 

---

**Bugs**

**1. catalogNumber `681` is showing up in query results for catalogNumber > 3000.**
[This CO](https://calvertmarinemuseum20250210-issue-2000.test.specifysystems.org/specify/view/collectionobject/30721/) is still showing up in the results for the query catalogNumber > 3000 with Series checked. Marking this as a bug because `681` is not a result in the same query without Series checked.

Link to Query: https://calvertmarinemuseum20250210-issue-2000.test.specifysystems.org/specify/view/collectionobject/30721/ 

I checked the Audit Log for this CO and it was changed from `0000006810`->`000000681`, so maybe that could be affecting it? 
<img width="400" alt="Screenshot 2025-04-21 at 8 48 47 AM" src="https://github.com/user-attachments/assets/be20ade5-a728-4910-9409-0ffb1483199d" />

2025-04-28 18:37 UTC, acwhite211 commented
@specify/ux-testing We're going to push ordering and grouping related errors that occur due to format parsing of the catalog number to a later PR.  So, we are just testing the functionality of series queries with the knowledge the catalog grouping will be improved in the future.  Thanks!

2025-04-29 21:56 UTC, acwhite211 commented
Created a follow-up issue for handling catalog number format parsing https://github.com/specify/specify7/issues/6457

2025-04-30 13:24 UTC, pashiav approved these changes
- [X] verify series checkbox is present only when Cat num is one of the field 
- [X] verify Distinct is read only 
- [X] Verify you can check Distinct and that Series become readonly 
- [X] Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together 
- [X] Verify that the consecutive cat numbers are displayed as a range 

---

Looks good! This PR is working as expected.

2025-04-30 19:21 UTC, Areyes42 requested changes
-   [x] verify series checkbox is present only when Cat num is one of the field
-  [x]  verify Distinct is read only
-   [x] Verify you can check Distinct and that Series become readonly
-  [x]  Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together
-  [x]  Verify that the consecutive cat numbers are displayed as a range
***
Everything looks good for the most part! I noticed that a TypeError occurs if you run a query using series, but have the catalog number disabled in the results.

https://github.com/user-attachments/assets/56bf1e7a-22f8-4372-a3b5-3ecb4601c6c9

[Specify 7 Crash Report - 2025-04-30T17_58_11.334Z.txt](https://github.com/user-attachments/files/19983196/Specify.7.Crash.Report.-.2025-04-30T17_58_11.334Z.txt)

2025-05-05 14:36 UTC, acwhite211 commented
@CarolineDenis I think we need to hide the series button in the QB if the user hides the Catalog Number from the results.  This should fix the issue encountered by @Areyes42 

I have a solution that I can commit that will only run the series query logic if the Catalog Number field sets its display value to true.  But, from the user side, I think if would be better to just not allow the user to request a series query with the Catalog Number display set to false.

2025-05-08 14:37 UTC, acwhite211 commented
@Areyes42 @specify/ux-testing Pushed a fix for the series QB that was found on ciscollections.  Ready for retesting on that DB, thanks!

2025-05-08 14:47 UTC, acwhite211 approved these changes

2025-05-08 18:16 UTC, Areyes42 approved these changes
-  [x]  verify series checkbox is present only when Cat num is one of the field
-   [x] verify Distinct is read only
-  [x]  Verify you can check Distinct and that Series become readonly
-  [x]  Verify that all the records that have the same data for each field in your query and that have consecutive cat num are group together
-  [x]  Verify that the consecutive cat numbers are displayed as a range

* * *
Looks good!

2025-05-08 19:14 UTC, merged