Send RSS Export Feed notifications to the correct users
specify/specify7 pull request #4956
Opened 2024-05-27 17:32 UTC by melton-jason

Fixes #4267 

@specify/ux-testing 
Currently, these changes only affect the notifications if the update is successful. 
If a failure occurs, the past behavior should still be observed (only the user which initiated the RSS Export Feed Update receives a notification). Should the complete failure be sent to the user who started the RSS Export Feed Update (so that they can make changes/notify someone?), or should they also only receive a notification that the Update has failed and send a more complete notification to the `notifyUserId` of the Export Feed? 

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions
- Ensure you are logged in as a user which has permission to update the RSS Export Feed, but not the same user as specified in the `notifyUserId` ('Send completion notification to user') of the Export Feed
- Update the Export Feed from the User Tools menu 
- [ ] Ensure you receive a notification (without a link to the Export Feed zip) when the Export Feed update completes 
- [ ] Login as the user specified in the `notifyUserId` of the Export Feed and ensure you received a notification which contains a link to the zip

- Update the RSS Export Feed as the user specified as the `notifyUserId` of the Export Feed
- [ ] Ensure you only receive a single notification (containing the resulting zip)

2024-05-27 18:09 UTC, combs-a requested changes
### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions
- Ensure you are logged in as a user which has permission to update the RSS Export Feed, but not the same user as specified in the `notifyUserId` ('Send completion notification to user') of the Export Feed
- Update the Export Feed from the User Tools menu 
- [X] Ensure you receive a notification (without a link to the Export Feed zip) when the Export Feed update completes 
- [X] Login as the user specified in the `notifyUserId` of the Export Feed and ensure you received a notification which contains a link to the zip

First two checks passed! 🎉 

- Update the RSS Export Feed as the user specified as the `notifyUserId` of the Export Feed
- [ ] Ensure you only receive a single notification (containing the resulting zip)

Getting two notifications when doing it as the `notifyUserId` user, however.

![image](https://github.com/specify/specify7/assets/71564869/6e38b0e5-3755-462a-9b58-c8c4436dbb07)

Additionally, not setting the `notifyUserId` results in an export error, it should send the notification to the `userId` user instead (at least according to current documentation).

2024-05-27 20:16 UTC, combs-a approved these changes
### Testing instructions
- Ensure you are logged in as a user which has permission to update the RSS Export Feed, but not the same user as specified in the `notifyUserId` ('Send completion notification to user') of the Export Feed
- Update the Export Feed from the User Tools menu 
- [X] Ensure you receive a notification (without a link to the Export Feed zip) when the Export Feed update completes 
- [X] Login as the user specified in the `notifyUserId` of the Export Feed and ensure you received a notification which contains a link to the zip

- Update the RSS Export Feed as the user specified as the `notifyUserId` of the Export Feed
- [X] Ensure you only receive a single notification (containing the resulting zip)

- Edit the RSS Export Feed so that it no longer has a `notifyUserId` specified
- Login as the user specified by `userId` ('Run as user')
- Update the Export Feed from the User Tools menu
- [X] Ensure you only receive a single notification (containing the resulting zip)

- Login as a different user who has permission to update the RSS Export Feed
- Update the RSS Export Feed from the User Tools menu
- [X] Ensure you receive a notification (without a link to the Export Feed zip) when the Export Feed update completes
- [X] Login as the user specified in the `userId` of the Export Feed and ensure you received a notification which contains a link to the zip

Everything's looking great and works perfectly! 🎉

Talked about this in person, but I like the solution of sending a notification to let the person who updated the RSS feed know that it was completed, regardless if they're the one supposed to be getting the zip. The only potential concern is clutter, but it's better in my opinion so you don't have to log in as the other user to see if it updated.

This solution also only sends the error message to the user who updated the RSS feed, and not the user who is supposed to get the notification. Unsure of what would be the most desirable behavior in this situation, but personally, I think that the error notif only going to the person in charge of updating the feed makes sense.

2024-05-27 22:12 UTC, maxpatiiuk approved these changes

2024-05-28 15:01 UTC, grantfitzsimmons requested changes
Nevermind. Tested now and looks good.

2024-05-28 18:32 UTC, merged