Handle unassigned fields in preparation when calculating fields
specify/specify7 pull request #4968
Opened 2024-05-30 18:20 UTC by acwhite211

Fixes #4960

Handle unassigned fields in preparation when calculating fields.

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [ ] Add relevant issue to release milestone

### Testing instructions

2024-05-30 19:11 UTC, lexiclevenger requested changes
Both parts of the issue still occur in this branch. The crash reports I got look the same as before, but here they are just in case.

Part 1:
[Specify 7 Crash Report - 2024-05-30T19_04_19.635Z.txt](https://github.com/specify/specify7/files/15504722/Specify.7.Crash.Report.-.2024-05-30T19_04_19.635Z.txt)

Part 2: 
[Specify 7 Crash Report - 2024-05-30T19_04_50.328Z.txt](https://github.com/specify/specify7/files/15504727/Specify.7.Crash.Report.-.2024-05-30T19_04_50.328Z.txt)

2024-06-03 17:14 UTC, acwhite211 commented
It seems the problem wasn't that "quantityresolved" did not exist in the preparation, it was that the value of "quantityresolved" was set to Null.  I pushed a change to handle this, thanks @lexiclevenger for catching this issue.

2024-06-03 19:43 UTC, lexiclevenger requested changes
Testing instructions
Testing instructions here https://github.com/specify/specify7/issues/4960#issue-2321737514
---
Nice job! This fixed part 1 of the issue; the loan I linked can be opened and loans can be uploaded without filling the quantityresolved field.

However, part 2 of the issue, creating loans with unassociated items, still throws an error in this branch. 
[Specify 7 Crash Report - 2024-06-03T19_42_20.600Z.txt](https://github.com/user-attachments/files/15538891/Specify.7.Crash.Report.-.2024-06-03T19_42_20.600Z.txt)

2024-06-10 16:25 UTC, acwhite211 commented
Thanks, the line causing the second error is fixed now.

2024-06-10 16:49 UTC, lexiclevenger approved these changes
**Testing instructions**
Testing instructions here https://github.com/specify/specify7/issues/4960#issue-2321737514

---

Looks good! Both issues have been fixed. 👍

2024-06-10 17:09 UTC, sharadsw approved these changes

2024-06-10 18:08 UTC, emenslin approved these changes
### Testing instructions

- [x] Testing instructions here https://github.com/specify/specify7/issues/4960#issue-2321737514

Looks good, both issues seem to be fixed!

2024-06-10 18:14 UTC, merged