Define separate config for bulk carry forward
specify/specify7 pull request #5120
Opened 2024-07-19 20:57 UTC by CarolineDenis

Fixes #5114

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- Create a new CO record
- Save
- Click on the gear icon to access the form meta
- Enable the "Show Carry Forward Button" and "Show bulk carry forward count"
- Click on the gear icon next to "Show bulk carry forward count"
- [ ] Verify you cannot Uncheck a required field
- Define you bulk carry forward config
- Input a value higher than 2 for "Bulk Carry Forward Count"
- Click Carry Forward 
- [ ] Verify it respected you config

2024-07-22 21:13 UTC, sharadsw approved these changes

2024-07-23 14:41 UTC, emenslin requested changes
### Testing instructions

- Create a new CO record
- Save
- Click on the gear icon to access the form meta
- Enable the "Show Carry Forward Button" and "Show bulk carry forward count"
- Click on the gear icon next to "Show bulk carry forward count"
- [ ] Verify you cannot Uncheck a required field (set as required in Schema Config)
- Define you bulk carry forward config (might have to reload the page for the carry config to be applied)
- Input a value higher than 2 for "Bulk Carry Forward Count"
- Click Carry Forward 
- [ ] Verify it respected your config 

Can uncheck required fields 

When I unchecked Prep Type trying to carry forward threw an error and no records were created 
![Screenshot 2024-07-23 092635](https://github.com/user-attachments/assets/62ec27b4-66a3-4dfb-82a5-b141f30988ef)
[Specify 7 Crash Report - 2024-07-23T14_26_36.336Z.txt](https://github.com/user-attachments/files/16350428/Specify.7.Crash.Report.-.2024-07-23T14_26_36.336Z.txt)

When just cataloger is unchecked it creates the records anyway 

https://github.com/user-attachments/assets/def9048e-03d2-4fd6-ba59-b6ea6265d7ae

2024-07-23 14:51 UTC, emenslin commented
Also forgot to include this in my initial comment but this is really annoying if there's anyway to fix it 

https://github.com/user-attachments/assets/00ff8d0d-866f-417b-b508-b8a3d395bbe5

If you hover over the carry forward gear the tool tip for it blocks the bulk carry forward gear so you can't do anything until it goes away

2024-07-23 15:41 UTC, alesan99 commented
Currently nested configurations are shared between bulk and normal configs. I originally encountered it with Preparations but I've reproduced it below:

https://github.com/user-attachments/assets/2cd6bbfd-eb3e-4a76-a6ab-5db95c6947de

2024-07-23 17:21 UTC, emenslin approved these changes
### Testing instructions

- Create a new CO record
- Save
- Click on the gear icon to access the form meta
- Enable the "Show Carry Forward Button" and "Show bulk carry forward count"
- Click on the gear icon next to "Show bulk carry forward count"
- [x] Verify you cannot Uncheck a required field (set as required in Schema Config)
- Define you bulk carry forward config (might have to reload the page for the carry config to be applied)
- Input a value higher than 2 for "Bulk Carry Forward Count"
- Click Carry Forward 
- [x] Verify it respected your config 

Cannot uncheck required fields anymore, works as expected
![Screenshot 2024-07-23 121545](https://github.com/user-attachments/assets/2d83fab9-0457-4923-af00-263a3f3b70d2)

2024-07-23 17:53 UTC, alesan99 approved these changes
- Create a new CO record
- Save
- Click on the gear icon to access the form meta
- Enable the "Show Carry Forward Button" and "Show bulk carry forward count"
- Click on the gear icon next to "Show bulk carry forward count"
- [x] Verify you cannot Uncheck a required field (set as required in Schema Config)
- Define you bulk carry forward config (might have to reload the page for the carry config to be applied)
- Input a value higher than 2 for "Bulk Carry Forward Count"
- Click Carry Forward 
- [x] Verify it respected your config 

My issue is resolved! All settings between bulk and normal carry are fully separate 👍

Everything else is working as expected as well. All changes to the config appear to apply instantly without having to reload too

2024-07-23 23:25 UTC, maxpatiiuk approved these changes

2024-07-23 23:25 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/FormMeta/CarryForward.tsx
> +                        field.overrides.isRequired))
could you extract this into a variable to not duplicate it twice? it's a pretty complex expression

2024-07-24 13:31 UTC, merged

2024-09-24 01:43 UTC, specifysoftware commented
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-9-7-release-announcement/1979/1