Add COGType picklist to COG and add COGTypeType picklist
specify/specify7 pull request #5200
Opened 2024-08-07 15:46 UTC by CarolineDenis

Fixes #5118 

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

TODO

2024-08-07 15:49 UTC, CarolineDenis commented
Reminder: 
- The COG has a COGType pick list (defined by user) 
- The COGType has a Type pick list (read-only, one of those three values: Discrete - Consolidated - Drill Core)

2024-08-12 18:47 UTC, CarolineDenis commented on specifyweb/specify/migrations/0004_cogtype_picklist.py
> +            isRequired=False
do we want this true or false?

2024-08-13 18:51 UTC, sharadsw requested changes
A note on picklist formatter:
Like in the COType PR, we will need a default formatter for the picklist. Looks like #5118 requires the formatter to be `cogtype -> type` but I'm not sure that would enough since each COGtype has an associated type (Drill Core, Discrete, Consolidated) and so the picklist would just have multiple entries for the same types. Maybe a better formatter would be `name + type` but either way we would need to create a default formatter (which involves changing a xml file in Sp6)

2024-08-14 18:29 UTC, sharadsw approved these changes

2024-08-26 20:21 UTC, sharadsw commented
NOTE:
Pushed commits to fix the default picklist created in the geo migration and also the fix the update queries for cog -> cogtype and cogtype -> type. 
- Cog -> cogtype will be a type 1 picklist containing names of all cogtypes in the db
- Cogtype -> type will be a type 0 picklist containing values Drill Core, Discrete and Consolidated

Any default formatter we define for the Cog -> cogtype picklist in future will have to be named `CollectionObjectGroupType` for it to be used automatically for this picklist.

2024-09-04 18:44 UTC, CarolineDenis commented
Added to https://github.com/specify/specify7/pull/5257/files

2024-09-04 18:44 UTC, closed without merging