Handle camel case geo table for localization
specify/specify7 pull request #5220
Opened 2024-08-13 16:51 UTC by CarolineDenis

Fixes #5192

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- Customize the schema for collectionobjectgroup and collectionobjectgroupjoin
- Go to the query builder (/specify/query/new/collectionobjectgroup/) or to the form (/specify/view/collectionobjectgroup/new/)
- [ ] Verify that the custom visibility/labels/descriptions are respected

2024-08-13 18:01 UTC, sharadsw approved these changes

2024-08-13 19:52 UTC, CarolineDenis commented
NOTES: 
Might not be necessary after https://github.com/specify/specify7/pull/5221/files#diff-95fc44b05f92ce9aaaa555f15ed1b3da6e4044fb3c851ea43ae0a42561e6068f

2024-08-13 19:54 UTC, emenslin approved these changes
### Testing instructions

- Customize the schema for collectionobjectgroup and collectionobjectgroupjoin
- Go to the query builder (/specify/query/new/collectionobjectgroup/) or to the form (/specify/view/collectionobjectgroup/new/)
- [x] Verify that the custom visibility/labels/descriptions are respected

Looks good, all customizations seem to be respected in both the forms and the query builder

2024-08-13 20:24 UTC, lexiclevenger approved these changes
### Testing instructions

- Customize the schema for collectionobjectgroup and collectionobjectgroupjoin
- Go to the query builder (/specify/query/new/collectionobjectgroup/) or to the form (/specify/view/collectionobjectgroup/new/)
- [x] Verify that the custom visibility/labels/descriptions are respected

---

Looks good! 👍

2024-08-13 23:12 UTC, Areyes42 approved these changes
### Testing instructions

-   Customize the schema for collectionobjectgroup and collectionobjectgroupjoin
-   Go to the query builder (/specify/query/new/collectionobjectgroup/) or to the form (/specify/view/collectionobjectgroup/new/)
-  [x]  Verify that the custom visibility/labels/descriptions are respected
***
Looks good!!

2024-08-14 00:28 UTC, maxpatiiuk reviewed
hmm, this looks like a back-end bug, maybe migration-related.
why is this being worked-around on the front-end?

2024-08-14 01:15 UTC, grantfitzsimmons requested changes
@maxpatiiuk I was thinking the same thing. Isn't this something we should fix in the migrations?

2024-08-14 13:49 UTC, CarolineDenis commented
@maxpatiiuk @grantfitzsimmons yes it will be done in: https://github.com/specify/specify7/pull/5221

2024-08-19 20:50 UTC, melton-jason reviewed
Can this be closed now that #5221 is merged? 
Or is the plan to include this frontend workaround regardless?

2024-08-19 20:50 UTC, melton-jason commented on specifyweb/frontend/js_src/lib/components/DataModel/specifyTable.ts
> +      };
If we do need a workaround on the frontend, would `caseInsensitiveHash` be fine here?
(Though I am mostly worried about the difference in performance with `caseInsensitiveHash` in this case, so the way it is currently is probably fine IF a workaround is needed). 

```suggestion
    this.localization = caseInsensitiveHash(
      getSchemaLocalization(),
      this.name
    ) ?? {
      items: {},
    };
```

2024-08-21 14:50 UTC, closed without merging