Add COG children picker to forms
specify/specify7 pull request #5279
Opened 2024-09-17 15:02 UTC by CarolineDenis

Fixes #5185

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [ ] Add relevant issue to release milestone

### Testing instructions

TODO

2024-10-21 19:52 UTC, grantfitzsimmons requested changes
To make this work, I had to manually add `CollectionObjectGroupType` records.

```sql
INSERT INTO ku_fish.collectionobjectgrouptype (COGTypeID, Name, Type, Version, TimestampCreated, TimestampModified,
                                               CollectionID, CreatedByAgentID, ModifiedByAgentID)
VALUES (1, 'Consolidated', 'Consolidated', 0, '2024-10-21 14:03:04.000000', '2024-10-21 14:03:04.000000', 4, 3, 3);

INSERT INTO ku_fish.collectionobjectgrouptype (COGTypeID, Name, Type, Version, TimestampCreated, TimestampModified,
                                               CollectionID, CreatedByAgentID, ModifiedByAgentID)
VALUES (2, 'Drill Core', 'Drill Core', 0, '2024-10-21 14:03:04.000000', '2024-10-21 14:03:04.000000', 4, 3, 3);

INSERT INTO ku_fish.collectionobjectgrouptype (COGTypeID, Name, Type, Version, TimestampCreated, TimestampModified,
                                               CollectionID, CreatedByAgentID, ModifiedByAgentID)
VALUES (3, 'Discrete', 'Discrete', 0, '2024-10-21 14:03:04.000000', '2024-10-21 14:03:04.000000', 4, 3, 3);
```


> ### Testing instructions
> 
> - go to data entry and select Collection Object Group 
> - define a name and select a cogType

This could **only** be done after manually running the SQL command above. This _should_ be solved in #5215, so we need to make sure that is actually resolved.

> - [ ] verify you can create a new CO child and save the CO 

Only if I create it via the `childCojos` relationship. The `cojo` relationship does not preserve the children on the form.

https://github.com/user-attachments/assets/190d0806-f1d7-4261-8604-b7d9c2de0c2c

> - [X] verify you can save the main COG form 
> - [ ] verify after refresh the CO child is still there 

See above for `cojo`

> - [X] verify you can create a new COG child and save the COG 
> - [X] verify you can save the main COG form 
> - [] verify after refresh the COG child is still there 

See above for `cojo`, only preserved for `childCojos`

> - [X] verify you can add one CO child using query builder
> - [X] verify you can save the main COG form 
> - [ ] verify after refresh the CO child is still there 
> - [ ] verify you can add several CO children using query builder

Each time I used the QB to return a list of all COs, searching only (any) Catalog Number, I would select a range of results. After selection, an item in the list would always be duplicated (recreated several times).

https://github.com/user-attachments/assets/d1dcea72-1be9-4a12-a7c8-7278b571dd7b


[Specify 7 Crash Report - 2024-10-21T19_28_33.009Z.txt](https://github.com/user-attachments/files/17466119/Specify.7.Crash.Report.-.2024-10-21T19_28_33.009Z.txt)

This is an **existing issue**, but it does affect this component, so I've reported it here:
https://github.com/specify/specify7/issues/5335

> - [X] verify you can save the main COG form 
> - [ ] verify after refresh the CO child is still there

See above for `cojo`, only preserved for `childCojos`

> - [X] verify you can add one COG child using query builder
> - [X] verify you can save the main COG form 
> - [X] verify after refresh the COG child is still there 
> - [X] verify you can add several COG children using query builder

Same issue reported above (#5335)

> - [X] verify you can save the main COG form 
> - [ ] verify after refresh the COG child is still there

See above for `cojo`, only preserved for `childCojos`

> - [X] verify you can delete any children 

I had some trouble with this being consistently enforced, as sometimes the children I added wouldn't be saved, but I can't recreate consistently. Would like other @specify/ux-testing members to see if they can identify the issue.

> - [X] verify you can uncollapse each child 
> - [ ] verify you can add a parent cojo 

I cannot add a parent Cojo. When I try to create a COJO, I can't set it's parent, therefore I see:
```
BusinessRuleException at /api/specify/collectionobjectgroupjoin/ Both childcog and childco cannot be null.
```

[Specify 7 Crash Report - 2024-10-21T19_47_16.967Z.txt](https://github.com/user-attachments/files/17466288/Specify.7.Crash.Report.-.2024-10-21T19_47_16.967Z.txt)

2024-10-21 21:13 UTC, sharadsw requested changes

2024-10-22 03:38 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/FormCells/COJODialog.tsx
> +  );
I believe we are using the name `state` in several components for this purpose.
The name is generic, but useful in simple components that have only one or two states.

2024-10-22 03:38 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/FormCells/COJODialog.tsx
> +  >(undefined);
💯

2024-10-22 03:38 UTC, maxpatiiuk commented on specifyweb/frontend/js_src/lib/components/FormCells/COJODialog.tsx
> +                {localized(table.label)}
`localized()` probably not needed here

2024-10-23 13:31 UTC, grantfitzsimmons requested changes
In addition to my previous review, I wanted to mention that I can not always delete an item from a COG, and after a refresh it will return:

https://github.com/user-attachments/assets/b92ea2da-5bd3-419f-a2ac-aa505290feca

See the save button does not get triggered:

https://github.com/user-attachments/assets/87de0afe-db01-4604-9af3-1fdca6d8130a

2024-10-29 19:08 UTC, CarolineDenis commented
TODO: 
- Remove cojo on cog ? And only keep parentCojo

2024-10-31 14:51 UTC, sharadsw approved these changes

2024-10-31 16:41 UTC, emenslin requested changes
### Testing instructions

- go to data entry and select Collection Object Group 
- define a name and select a cogType 
- [x] verify you can create a new CO child and save the CO 
- [x] verify you can save the main COG form 
- [x] verify after refresh the CO child is still there 
- [x] verify you can create a new COG child and save the COG 
- [x] verify you can save the main COG form 
- [x] verify after refresh the COG child is still there 
- [x] verify you can add one CO child using query builder
- [x] verify you can save the main COG form 
- [x] verify after refresh the CO child is still there 
- [x] verify you can add several CO children using query builder
- [ ] verify you can save the main COG form 
- [ ] verify after refresh the CO child is still there
- [x] verify you can add one COG child using query builder
- [x] verify you can save the main COG form 
- [x] verify after refresh the COG child is still there 
- [x] verify you can add several COG children using query builder
- [x] verify you can save the main COG form 
- [x] verify after refresh the COG child is still there
- [x] verify you can delete any children 
- [x] verify you can uncollapse each child 
- [x] verify you can add a parent cojo 

--- 

Adding several CO children with the query builder throws an error when you try to save the COG. Adding just one CO child does work though 

https://github.com/user-attachments/assets/d375ea7c-554f-48a4-9328-5052c0fbcefe


[Specify 7 Crash Report - 2024-10-31T16_16_00.610Z.txt](https://github.com/user-attachments/files/17590329/Specify.7.Crash.Report.-.2024-10-31T16_16_00.610Z.txt)

Everything else appears to be working though!

2024-10-31 16:48 UTC, CarolineDenis commented
@specify/ux-testing 
When adding several children using the QB, it can happen that a row is being duplicated.
This is a known issue https://github.com/specify/specify7/issues/5335
It will not be addressed in this pr. 
Just delete the row that have been duplicated before saving your cog

2024-10-31 17:15 UTC, grantfitzsimmons requested changes
This migration can correctly be rolled back (`0010_updateDelete_parentcojo`): ❤️ 
```
specify@494f280856e6:/opt/specify7$ ve/bin/python manage.py migrate specify 0005_collectionobjectgroup_parentcojo
Operations to perform:
  Target specific migration: 0005_collectionobjectgroup_parentcojo, from specify
Running migrations:
  Rendering model states... DONE
  Unapplying specify.0010_updateDelete_parentcojo... OK
  Unapplying specify.0009_tectonic_ranks... OK
  Unapplying specify.0008_ageCitations_fix... OK
  Unapplying specify.0007_schema_config_update... OK
  Unapplying specify.0006_fix_tectonic_tree_fields... OK
specify@494f280856e6:/opt/specify7$ 
```

> ### Testing instructions

FYI, the "COGviewDef.txt" file for testing is not usable–
<img width="661" alt="image" src="https://github.com/user-attachments/assets/3dffde49-eddc-40c9-ba92-d2f8e2609906">

But I created my own 😇  which will eventually get folded into our static files in a PR I'll open for https://github.com/specify/specify7/issues/5311

If anyone else wants it, here you go: [geo.common.views.xml.zip](https://github.com/user-attachments/files/17590977/better.common.views.xml.zip)

<img width="853" alt="image" src="https://github.com/user-attachments/assets/89585f77-ebc1-4195-a36a-dd1a8a216da8">

> - go to data entry and select Collection Object Group 
> - define a name and select a cogType 
> - [X] verify you can create a new CO child and save the CO 
> - [X] verify you can save the main COG form 
> - [X] verify after refresh the CO child is still there 
> - [X] verify you can create a new COG child and save the COG 
> - [X] verify you can save the main COG form 
> - [X] verify after refresh the COG child is still there 
> - [X] verify you can add one CO child using query builder
> - [X] verify you can save the main COG form 
> - [X] verify after refresh the CO child is still there 
> - [X] verify you can add several CO children using query builder
> - [X] verify you can save the main COG form 
> - [X] verify after refresh the CO child is still there
> - [X] verify you can add one COG child using query builder
> - [X] verify you can save the main COG form 
> - [X] verify after refresh the COG child is still there 
> - [X] verify you can add several COG children using query builder
> - [X] verify you can save the main COG form 
> - [X] verify after refresh the COG child is still there
> - [X] verify you can delete any children 
> - [X] verify you can uncollapse each child 
> - [ ] verify you can add a parent cojo 
> 

<img width="880" alt="image" src="https://github.com/user-attachments/assets/5de28819-3a89-4042-abd4-2e41b9eafb78">

After creating a new `CollectionObjectGroupJoin` record via the `parentCojo` query combo box, I get this error upon saving:
```
BusinessRuleException at /api/specify/collectionobjectgroupjoin/ Both childcog and childco cannot be null.
```
Seems like it might not get set appropriately.

[Specify 7 Crash Report - 2024-10-31T17_14_03.769Z.txt](https://github.com/user-attachments/files/17591010/Specify.7.Crash.Report.-.2024-10-31T17_14_03.769Z.txt)


> - you should not be able to add a COGChild to a COG that is already in use in another COG, when doing so an error should be thrown saying that the COGChild is already used 

I feel pretty strongly that this error should be caught **before** crashing. No user should ever see an _error_ if we can catch it and prevent saving with a relevant tooltip.

2024-10-31 17:35 UTC, grantfitzsimmons approved these changes
I spoke to @CarolineDenis – the plan is to add the ability to set a `parentCojo` in January (https://github.com/specify/specify7/issues/5357)

Also I no longer get duplicate items when selecting and adding more than 5 items using the QB

2024-10-31 17:57 UTC, acwhite211 approved these changes

2024-10-31 18:49 UTC, emenslin approved these changes
### Testing instructions

- go to data entry and select Collection Object Group 
- define a name and select a cogType 
- [x] verify you can create a new CO child and save the CO 
- [x] verify you can save the main COG form 
- [x] verify after refresh the CO child is still there 
- [x] verify you can create a new COG child and save the COG 
- [x] verify you can save the main COG form 
- [x] verify after refresh the COG child is still there 
- [x] verify you can add one CO child using query builder
- [x] verify you can save the main COG form 
- [x] verify after refresh the CO child is still there 
- [x] verify you can add several CO children using query builder
- [x] verify you can save the main COG form 
- [x] verify after refresh the CO child is still there
- [x] verify you can add one COG child using query builder
- [x] verify you can save the main COG form 
- [x] verify after refresh the COG child is still there 
- [x] verify you can add several COG children using query builder
- [x] verify you can save the main COG form 
- [x] verify after refresh the COG child is still there
- [x] verify you can delete any children 
- [x] verify you can uncollapse each child 
- you should not be able to add a COGChild to a COG that is already in use in another COG, when doing so an error should be thrown saying that the COGChild is already used 

Looks good, can now add multiple CO at once!

2024-11-01 13:26 UTC, CarolineDenis commented
Closed in favor of https://github.com/specify/specify7/pull/5360

2024-11-01 13:45 UTC, closed without merging