Add tectonic default ranks
specify/specify7 pull request #5316
Opened 2024-10-08 16:55 UTC by CarolineDenis

Fixes #5294

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

2024-10-10 18:34 UTC, CarolineDenis commented on specifyweb/specify/models_by_table_id.py
> +#TODO: do we need to add tectnocUnit to this file?
add age tables and tectonic tables. 
Order has an importance?

2024-10-11 16:44 UTC, CarolineDenis commented on specifyweb/specify/tree_ranks.py
> +    'tectonic_unit': 40,
which of the two format do we need?

2024-10-11 18:14 UTC, CarolineDenis commented on specifyweb/stored_queries/execution.py
> +    if model is models.TectonicUnitTreeDefItem:
this line prevents from querying for tectonic unit item on form when adding the def item in the relationship

2024-10-14 16:12 UTC, sharadsw approved these changes

2024-10-21 14:55 UTC, combs-a approved these changes
### Testing instructions
- Open Tectonic Tree
- Verify the ranks below are present
- - [X] Superstructure
- - [X] Tectonic domain
- - [X] Tectonic subdomain
- - [X] Tectonic unit
- - [X] Tectonic subunit
- [X] Verify there is a root node 

Tested on ChadronTest. All the ranks and the root node was there, looks good.

![image](https://github.com/user-attachments/assets/0feb85dc-5420-42c2-bd63-e593ddf5f93d)

2024-10-21 17:08 UTC, grantfitzsimmons requested changes
Looks good in the app, but please add the migration explanation and other metadata to the [**Migrations Description**](https://docs.google.com/document/d/1a74C7NnAXtkynn0KAHVd6g7lXXj_n-GJ1LS68IYqjAs/edit?tab=t.0#heading=h.bhqvg1cfzp5r)

We should try to document these as we go along! Probably best to even link to the PR.

Note that this migration will need to be recreated when new disciplines are added in the future.

The only issue I encountered was reverting this migration. See below:
```sh
specify@260f0e593b10:/opt/specify7$ ve/bin/python manage.py showmigrations specify

specify
 [X] 0001_initial
 [X] 0002_geo
 [X] 0003_cotype_picklist
 [X] 0004_stratigraphy_age
 [X] 0005_collectionobjectgroup_parentcojo
 [X] 0006_fix_tectonic_tree_fields
 [X] 0007_tectonic_ranks
specify@260f0e593b10:/opt/specify7$ 
specify@260f0e593b10:/opt/specify7$ ve/bin/python manage.py migrate specify 0006_fix_tectonic_tree_fields

Operations to perform:
  Target specific migration: 0006_fix_tectonic_tree_fields, from specify
Running migrations:
  Rendering model states... DONE
  Unapplying specify.0007_tectonic_ranks...Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 121, in migrate
    state = self._migrate_all_backwards(plan, full_plan, fake=fake)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 196, in _migrate_all_backwards
    self.unapply_migration(states[migration], migration, fake=fake)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 252, in unapply_migration
    state = migration.unapply(state, schema_editor)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/migration.py", line 174, in unapply
    operation.database_backwards(self.app_label, schema_editor, from_state, to_state)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 196, in database_backwards
    self.reverse_code(from_state.apps, schema_editor)
  File "/opt/specify7/specifyweb/specify/migrations/0007_tectonic_ranks.py", line 118, in revert_cosolidated_python_django_migration_operations
    revert_default_tectonic_ranks(apps, schema_editor)
  File "/opt/specify7/specifyweb/specify/migrations/0007_tectonic_ranks.py", line 64, in revert_default_tectonic_ranks
    tectonic_tree_def.delete()
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/query.py", line 745, in delete
    collector.collect(del_query)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/deletion.py", line 302, in collect
    raise ProtectedError(
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'TectonicUnitTreeDef' because they are referenced through protected foreign keys: 'TectonicUnitTreeDefItem.treedef', 'TectonicUnit.definition'.", {<TectonicUnitTreeDefItem: TectonicUnitTreeDefItem object (1)>, <TectonicUnitTreeDefItem: TectonicUnitTreeDefItem object (2)>, <TectonicUnitTreeDefItem: TectonicUnitTreeDefItem object (3)>, <TectonicUnitTreeDefItem: TectonicUnitTreeDefItem object (4)>, <TectonicUnitTreeDefItem: TectonicUnitTreeDefItem object (5)>, <TectonicUnitTreeDefItem: TectonicUnitTreeDefItem object (6)>, <TectonicUnit: TectonicUnit object (1)>})
specify@260f0e593b10:/opt/specify7$ 
```

2024-10-23 20:02 UTC, grantfitzsimmons requested changes
```
specify@f494bdad9830:/opt/specify7$ ve/bin/python manage.py migrate specify 0006_fix_tectonic_tree_fields
Operations to perform:
  Target specific migration: 0006_fix_tectonic_tree_fields, from specify
Running migrations:
  Rendering model states... DONE
  Unapplying specify.0007_tectonic_ranks...Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 121, in migrate
    state = self._migrate_all_backwards(plan, full_plan, fake=fake)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 196, in _migrate_all_backwards
    self.unapply_migration(states[migration], migration, fake=fake)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 252, in unapply_migration
    state = migration.unapply(state, schema_editor)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/migration.py", line 174, in unapply
    operation.database_backwards(self.app_label, schema_editor, from_state, to_state)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 196, in database_backwards
    self.reverse_code(from_state.apps, schema_editor)
  File "/opt/specify7/specifyweb/specify/migrations/0007_tectonic_ranks.py", line 118, in revert_cosolidated_python_django_migration_operations
    revert_default_tectonic_ranks(apps, schema_editor)
  File "/opt/specify7/specifyweb/specify/migrations/0007_tectonic_ranks.py", line 64, in revert_default_tectonic_ranks
    tectonic_tree_def.delete()
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/query.py", line 745, in delete
    collector.collect(del_query)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/deletion.py", line 302, in collect
    raise ProtectedError(
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'TectonicUnitTreeDef' because they are referenced through protected foreign keys: 'TectonicUnitTreeDefItem.treedef', 'TectonicUnit.definition'.", {<TectonicUnitTreeDefItem: TectonicUnitTreeDefItem object (1)>, <TectonicUnitTreeDefItem: TectonicUnitTreeDefItem object (2)>, <TectonicUnitTreeDefItem: TectonicUnitTreeDefItem object (3)>, <TectonicUnitTreeDefItem: TectonicUnitTreeDefItem object (4)>, <TectonicUnitTreeDefItem: TectonicUnitTreeDefItem object (5)>, <TectonicUnitTreeDefItem: TectonicUnitTreeDefItem object (6)>, <TectonicUnit: TectonicUnit object (1)>})
specify@f494bdad9830:/opt/specify7$ 
What's next:
    Try Docker Debug for seamless, persistent debugging tools in any container or image → docker debug specify7-specify7-1
    Learn more at https://docs.docker.com/go/debug-cli/
```

@CarolineDenis Could you revert successfully?

2024-10-23 21:02 UTC, grantfitzsimmons approved these changes
```
~/GitHub/specify7 on issue-5316 *1 !2 ❯ docker exec -it specify7-specify7-1 /bin/bash                                                                          Py specify7 at 04:01:11 PM
specify@82862d65616e:/opt/specify7$ ve/bin/python manage.py migrate specify 0006_fix_tectonic_tree_fields
Operations to perform:
  Target specific migration: 0006_fix_tectonic_tree_fields, from specify
Running migrations:
  Rendering model states... DONE
  Unapplying specify.0007_tectonic_ranks... OK
specify@82862d65616e:/opt/specify7$ 
```

2024-10-30 15:45 UTC, acwhite211 approved these changes

2024-10-30 16:24 UTC, merged