Fix tree structure issues due to an old WorkBench bug
specify/specify7 pull request #5366
Opened 2024-11-01 19:43 UTC by grantfitzsimmons

Fixes #5131

This came up again from a user that was self-hosted so I thought this could be a more meaningful fix.

This fixes an issue due to a bug in the WorkBench prior to 7.9.0 that did not
set accepted nodes to IsAccepted = 1 when they were not synonyms.
https://github.com/specify/specify7/issues/5131

This was done on all hosted databases, but self-hosted users are still potentially facing bad tree structure errors due to this.

The migration is also fully reversible.

```
specify@c82512644edc:/opt/specify7$ ve/bin/python manage.py migrate specify 0010_updateDelete_parentcojo
Operations to perform:
  Target specific migration: 0010_updateDelete_parentcojo, from specify
Running migrations:
  Rendering model states... DONE
  Unapplying specify.0011_fix_accepted_tax... OK
```

### Testing instructions

_I made this hard since I fixed all cases on hosted databases and on the test panel... but the scope of this is pretty small. These testing instructions are overkill._

Essentially, this is running the following SQL statement:
`UPDATE taxon t1 SET IsAccepted = TRUE WHERE t1.IsAccepted = 0 AND t1.AcceptedId IS NULL`

**Before running the migration:**
1. On `production`, manually modify `taxon` records (via SQL) to set `IsAccepted` to `0` (false) in cases where that record is not a synonym
2. Try to create a child under that node in Specify (should get a "bad tree structure" error)

**After running the migration:**
1. After starting the container on `issue-5131`, try to create a child under that node in Specify (should no longer see a "bad tree structure" error
2. Check that the modified `taxon` record now is shown as accepted (`IsAccepted` = `1` (true)) in all cases where it is not a synonym.
3. Check that all `taxon` records that are synonyms are not now accepted.

2024-11-01 19:45 UTC, grantfitzsimmons commented on specifyweb/specify/migrations/0011_fix_accepted_taxon.py
> +        ('specify', '0010_updateDelete_parentcojo'),
TODO: Update this and the migration number to the appropriate iteration based on the current `production` branch at the time of merge

2024-11-01 19:55 UTC, CarolineDenis approved these changes

2024-11-05 04:25 UTC, maxpatiiuk approved these changes

2025-01-10 18:14 UTC, grantfitzsimmons commented
@CarolineDenis This has been updated to be completed after the last current geo migration (after `0019_remove_parentCog`)

2025-01-15 18:20 UTC, Areyes42 requested changes
**Before running the migration:**

- [x]  Try to create a child under that node in Specify (should get a "bad tree structure" error)

**After running the migration:**

- [x]  After starting the container on `issue-5131`, try to create a child under that node in Specify (should no longer see a "bad tree structure" error)
- [x]  Check that the modified `taxon` record now is shown as accepted (`IsAccepted` = `1` (true)) in all cases where it is not a synonym.
- [x]  Check that all `taxon` records that are synonyms are not now accepted.
***
Accepted states look good after migrations; however, it looks like this created a new issue with child node creation. When creating a new child, Specify disregards the taxon rank chosen in the creation dialog (See recordings). This behavior is not present in production.

![Screenshot 2025-01-15 at 12 08 12 PM](https://github.com/user-attachments/assets/04e6a6f5-c675-4cd2-a503-f071deeb58f6)

issue-5131:

https://github.com/user-attachments/assets/5a0d782f-804a-4d59-a9ff-548f16479de0

Production:

https://github.com/user-attachments/assets/8b4976f8-f9ef-4a00-8d77-07bd7c2e575a

2025-01-15 19:13 UTC, grantfitzsimmons commented
@Areyes42 Can you test this again now that the latest changes from `production` are included in this branch?

2025-01-15 19:30 UTC, Areyes42 approved these changes
Looks good now!

2025-01-17 19:59 UTC, grantfitzsimmons commented on specifyweb/specify/migrations/0011_fix_accepted_taxon.py
> +        ('specify', '0010_updateDelete_parentcojo'),
Added this to a new app instead, `patches`

2025-02-14 20:59 UTC, combs-a approved these changes
Post-running the migration, everything looks good and works perfectly. Set all of the tree nodes' isAccepted to 0, switched to the branch and rebuilt the containers, and they were all set to 1 except for synonymized nodes. Was able to add children to the tree again.

2025-03-10 19:50 UTC, merged