Add geo trees to tree creation tool
specify/specify7 pull request #5372
Opened 2024-11-05 15:52 UTC by CarolineDenis

Fixes #5371

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- open tree viewer 
- click add a new tree 
- [ ] verify you can add each of the 3 new trees: Rocks - Minerals - Meteorites

2024-11-05 17:17 UTC, sharadsw approved these changes

2024-11-15 15:20 UTC, alesan99 requested changes
### Testing instructions

- open tree viewer 
- click add a new tree 
- [x] verify you can add each of the 3 new trees: Rocks - Minerals - Meteorites 

The new trees and their ranks are created correctly 👍👍👍👍

I do have a request though
![image](https://github.com/user-attachments/assets/1cbc0555-c945-4edd-ad1c-20a98cb1d79a)

Could the Empty Tree option be moved back to the bottom?

2024-11-15 17:26 UTC, emenslin requested changes
### Testing instructions

- open tree viewer 
- click add a new tree 
- [x] verify you can add each of the 3 new trees: Rocks - Minerals - Meteorites 

Can add tree ranks in the create tree dialog 

https://github.com/user-attachments/assets/46e966f0-9f3b-4f23-8970-594113f8baf2

2024-11-15 17:33 UTC, alesan99 approved these changes

2024-11-15 20:56 UTC, emenslin approved these changes
### Testing instructions

- open tree viewer 
- click add a new tree 
- [x] verify you can add each of the 3 new trees: Rocks - Minerals - Meteorites 

Looks good, can add the new trees and can no longer add ranks in the create tree dialog

2024-11-15 21:25 UTC, merged