Add cojo to Schema Config
specify/specify7 pull request #5388
Opened 2024-11-07 18:13 UTC by sharadsw

Fixes #5386

The missing relationships were due to COG -> cojo and CO -> cojo not being present in Schema Config. There were some more missing fields like `createdByAgent` and `timestampCreated` but those are from migration issues. If we test this PR with a fresh db, those fields shouldn't be missing

⚠️ **Note:** This PR affects database migrations. See [migration testing instructions](https://specify.github.io/testing/pull_requests.html#prs-tagged-with-label-migration).

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions

- Go to schema config
- Select COG, COGT, or CO as base table
- Click on uniqueness rules
- Add new rule
- Scroll down to relationships
- [ ] Verify there are no empty fields/relationships

2024-11-07 18:21 UTC, CarolineDenis approved these changes

2024-11-08 16:02 UTC, alesan99 approved these changes
### Testing instructions

<!-- What are the steps to verify the fixes/changes in this PR? -->
<!-- Can part of that be replaced by automated tests? -->
- Go to schema config
- Select COG, COGT, or CO as base table
- Click on uniqueness rules
- Add new rule
- Scroll down to relationships
- [x] Verify there are no empty fields/relationships

![image](https://github.com/user-attachments/assets/ae6608b6-c7be-4de9-b03e-d65683c4825a)

No more blank relationships on those tables 👍

Side note: applying migrations on a production db still resulted in a single blank option (for children I think). Trying the migrations on a fresh db fixed it, but resulted in two children relationships appearing in the schema config, but its not related to this PR.

2024-11-08 16:17 UTC, emenslin requested changes
### Testing instructions

<!-- What are the steps to verify the fixes/changes in this PR? -->
<!-- Can part of that be replaced by automated tests? -->
- Go to schema config
- Select COG, COGT, or CO as base table
- Click on uniqueness rules
- Add new rule
- Scroll down to relationships
- [ ] Verify there are no empty fields/relationships

Tried on two dbs and both resulted in some of the relationships still being empty. I am willing to believe this is a db problem however if it is, then we need to figure out which dbs do work. Tried with kufish212 and kubirds20240606

![Screenshot 2024-11-08 095702](https://github.com/user-attachments/assets/04163950-6bfb-4412-be0d-606abd845c0d)

![image](https://github.com/user-attachments/assets/98704192-347f-4d4e-a030-125529615d6f)

2024-11-08 17:36 UTC, sharadsw commented
@emenslin It does seem like a db issue. I ssh'd into the kufish container and it looks like the migration in this PR didn't get applied at all. `kufish` is 5 migrations behind the latest:
```
specify
 [X] 0001_initial
 [X] 0002_geo
 [X] 0003_cotype_picklist
 [X] 0004_stratigraphy_age
 [X] 0005_collectionobjectgroup_parentcojo
 [X] 0006_fix_tectonic_tree_fields
 [X] 0007_schema_config_update
 [ ] 0008_ageCitations_fix
 [ ] 0009_tectonic_ranks
 [ ] 0010_updateDelete_parentcojo
 [ ] 0011_cascading_tree_nodes
 [ ] 0012_add_cojo_to_schema_config
```
I get this error when I try to apply those migrations:
```
django.db.utils.OperationalError: (1060, "Duplicate column name 'AbsoluteAgeCitationID'")
```

kubirds20240606 does have all migrations so it's strange that it has missing fields. 
```
specify
 [X] 0001_initial
 [X] 0002_geo
 [X] 0003_cotype_picklist
 [X] 0004_stratigraphy_age
 [X] 0005_collectionobjectgroup_parentcojo
 [X] 0006_fix_tectonic_tree_fields
 [X] 0007_schema_config_update
 [X] 0008_ageCitations_fix
 [X] 0009_tectonic_ranks
 [X] 0010_updateDelete_parentcojo
 [X] 0011_cascading_tree_nodes
 [X] 0012_add_cojo_to_schema_config
```
I noticed the fields in Schema config on that db are capitalized instead of camelCased. My guess is that the initial dump of that db already had an older version of the geo migration applied to it. The geo migration was changed later to use camelCased fields but those changes never got applied and so some newer fields never got added (parentCojo, createdByAgent and modifiedByAgent). I have manually reapplied all migrations to kubirds20240606 so it should work fine now

2024-11-08 18:21 UTC, sharadsw commented
Pushed a fix for the duplicate children field. However, this would have to be tested by created another copy of a db as it changes an old migration

2024-11-08 19:58 UTC, combs-a submitted a review, later dismissed
![image](https://github.com/user-attachments/assets/48e74576-e4d0-4df9-a9d3-1269b3a52d7a)

Still blank for me too, followed the migration testing instructions as well. This was done with a clone of ChadronTest. Might be a database problem, but it's a bit concerning that 3 DBs that have been tried had migration issues.

2024-11-08 21:14 UTC, sharadsw commented
Looks like #5384 has made the tectonic rank migration irreversible since the migration tries to delete the root rank when reversing, which is no longer allowed. I'll edit that migration and reapply migrations for the dbs mentioned in this PR.

2024-11-12 16:04 UTC, sharadsw commented
@combs-a Created a new db `ChadronTest_fix` where migration issues should be fixed

2024-11-12 16:38 UTC, pashiav requested changes
### Testing instructions

<!-- What are the steps to verify the fixes/changes in this PR? -->
<!-- Can part of that be replaced by automated tests? -->
- Go to schema config
- Select COG, COGT, or CO as base table
- Click on uniqueness rules
- Add new rule
- Scroll down to relationships
- [ ] Verify there are no empty fields/relationships
---

Empty field on COG. COGT, and CO do not have any empty fields!


https://cuic22024-issue-5386.test.specifysystems.org/specify/overlay/configure/uniqueness/collectionobjectgroup
<img width="1470" alt="Screenshot 2024-11-12 at 10 32 38 AM" src="https://github.com/user-attachments/assets/9540fb26-43ff-40be-9107-f854df50115e">

2024-11-12 17:38 UTC, sharadsw commented
@pashiav I have reapplied all migrations on that db, should be fixed now

2024-11-12 17:40 UTC, pashiav approved these changes

2024-11-12 17:40 UTC, sharadsw commented
If a field other than `COG -> cojo` is missing, it is probably due to migration issues.

DBs tested on this PR:
`kufish212`: corrupt db, cannot reverse migrations
`kubirds20240606`: manually reapplied all migrations
`ChadronTest_fix`: tectonic ranks migration cannot be reversed (and so `COG -> parentCojo` is missing)
`cuic22024`: manually reapplied all migrations

2024-11-12 19:29 UTC, merged