Prevent save when no CO child is marked as primary in a Consolidated COG
specify/specify7 pull request #5449
Opened 2024-12-05 20:48 UTC by sharadsw

Fixes #5427

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions

- Create a COG with a Consolidated type
- Add children
- [ ] Verify save is blocked when no Collection Object children are marked as primary
- [ ] Verify save is enabled when a CO child is marked as primary or the type is not Consolidated

2024-12-05 21:12 UTC, emenslin approved these changes
### Testing instructions

<!-- What are the steps to verify the fixes/changes in this PR? -->
<!-- Can part of that be replaced by automated tests? -->
- Create a COG with a Consolidated type
- Add children
- [x] Verify save is blocked when no Collection Object children are marked as primary
- [x] Verify any CO child can be set as primary when the type is Consolidated
- [x] Verify save is enabled when a CO child is marked as primary or the type is not Consolidated

Looks good!
![image](https://github.com/user-attachments/assets/17a93eb7-842f-4abc-9cfb-2a6ea7b5ae99)

2024-12-05 21:16 UTC, Areyes42 approved these changes
### Testing instructions

-   Create a COG with a Consolidated type
-   Add children
-   [x] Verify save is blocked when no Collection Object children are marked as primary
-   [x] Verify any CO child can be set as primary when the type is Consolidated
-  [x]  Verify save is enabled when a CO child is marked as primary or the type is not Consolidated
***
Everything looks good 👍👍

2024-12-05 21:52 UTC, Areyes42 requested changes
### Testing instructions

-   Create a COG with a Consolidated type
-   Add children
-   [ ] Verify save is blocked when no Collection Object children are marked as primary
-   [x] Verify any CO child can be set as primary when the type is Consolidated
-   [x] Verify save is enabled when a CO child is marked as primary or the type is not Consolidated

* * *
I retested this and found that if children are added during the initial COG creation, the save blocker functions as expected. However, if the COG is created first and children are added later, it allows saving even if no child is marked as primary.

Child added after COG is created:

https://github.com/user-attachments/assets/3d1230fa-f044-4c4d-bf65-66e50ccae7d5

Child added during initial COG creation (expected save block behavior):

https://github.com/user-attachments/assets/c5dc9c48-cbc9-4451-b381-f15aaa2de152

2024-12-06 15:23 UTC, sharadsw commented
@Areyes42 I'm not able to reproduce it locally or on https://geo20241205-issue-5427.test.specifysystems.org/specify/view/collectionobjectgroup/8/

It's strange. I think it might be a timing error since the code has to wait for a promise to resolve before it sets the save blocker. 
https://github.com/specify/specify7/blob/19cb35612dbd5519b6e31c6cd458684d12ee63f1/specifyweb/frontend/js_src/lib/components/DataModel/businessRuleDefs.ts#L213-L219

Maybe in your case you were able to save before the promise was resolved? I'm not sure how we can avoid that

2024-12-06 22:00 UTC, Areyes42 requested changes
### Testing instructions

-   Create a COG with a Consolidated type
-   Add children
-  [ ]  Verify save is blocked when no Collection Object children are marked as primary
-   [x] Verify any CO child can be set as primary when the type is Consolidated
-   [x] Verify save is enabled when a CO child is marked as primary or the type is not Consolidated
***
My previous issue is fixed when isPrimary is directly updated! However, I noticed that deleting children that are marked isPrimary still lets you save without the save block.

https://github.com/user-attachments/assets/d72ca832-81cc-44e9-85b2-fcff6d130bfc

2024-12-09 21:23 UTC, Areyes42 approved these changes
-   [x] Verify save is blocked when no Collection Object children are marked as primary
-   [x] Verify any CO child can be set as primary when the type is Consolidated
-   [x] Verify save is enabled when a CO child is marked as primary or the type is not Consolidated
***
Changes look good now. Nice job, Sharad! 👏

2024-12-10 14:23 UTC, CarolineDenis approved these changes

2024-12-10 15:05 UTC, merged