Support COT catalog number configurations in the Query Builder
specify/specify7 pull request #5485
Opened 2024-12-18 06:33 UTC by melton-jason

Fixes #5474
Related to #5232

Allows the selection of Collection Object Type (COT) Catalog Number formats in the Query Builder!: 

<img width="1434" alt="Screenshot 2024-12-17 at 11 34 05 PM" src="https://github.com/user-attachments/assets/5b187c81-0272-448b-aa5a-0ac86fe0bdea" />

---

There are two interesting edge cases which I have a considered and would like discussion over implementation (or new Issue(s) created if needed): 

**The field format on the queryfilter is not a catalogNumberFormatName for a COT (e.g., COT was deleted since Query Creation)**

- The query can still be run and returns results regardless of the edge case 
- Like in a picklist, the invalid format name is present in the format picklist
- Since the format can still be resolved to be a valid formatter, each filter still uses the format for validation until a valid COT is chosen  

https://github.com/user-attachments/assets/349b43ad-7671-4d2b-a18b-b5b5448435d8

**The field format on a COT can not be found in the UIFormatters file**

I imagine this case would elicit the most feedback, @specify/testing!
This could use some improvement and brainstorming of ideas!

- The query can still be run and returns results regardless of the edge case 
- The format selection still shows the COT name to the user
- However, behind the scenes Specify defaults to the Catalog Number format defined on the Collection
- This becomes apparent when the input of the filter is touched: 

https://github.com/user-attachments/assets/71cdbe5f-5df3-4e17-942d-9f6457eabd39

- For now, I have kept the error as an indicator of "something is wrong!" to the user
- If desired, it would be trivial for a more "relaxed" approach to this edge case 
  - Instead of defaulting to Collection -> CatNum Format, we can disable validation for filters which use the invalid COT. 

---

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good and
      self-explanatory (or properly documented)
- [ ] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions
- Create a CollectionObjectType with a Catalog Number Format Name which differs from that of the Collection's default Catalog Number format
  - You can run a query on the Collection table with the `Catalog Num Format Name` field to determine the  default format
-  Create a new Collection Object query, add Catalog Number to the query, and switch the type from `Any` to any of: 
   - Equal 
   - Greater than
   - Less than
   - Greater or Equal to
   - Less or Equal to
   - Between
   - In
   - (all other types-like Contains or Starts With- have validation disabled by default)
- [ ] Ensure that by default, the Collection's default Catalog Number format is enforced 
- Switch the Catalog Number format to the previously created Collection Object Type using the new gear icon and picklist 
- [ ] Ensure the input of the field is now validating based on the format defined on the chosen Collection Object Type
- Add one or more OR filters to the Catalog Number field (this can be done through the `+` button) with a type from the list above 
- [ ] Ensure each filter on the Catalog Number field with validation can independently have its own format
- [ ] Save the Query and refresh the page: the Query should load successfully
- [ ] Ensure the query returns correct results when using filters with multiple Catalog Number formats
  - You may need to create/modify Collection Object records with the desired Collection Object Type 
  - For reference see https://github.com/specify/specify7/pull/5431#issue-2716025555 
 
- If there is only one CollectionObjectType or all CollectionObjectTypes either don't specify a Catalog Number format or use the Collection's default, then the gear icon to select a formatter should not appear on Catalog Number
- `Collection Object -> Catalog Number` along with formatted/aggregated fields are the **_only_** filters which should have the gear icon to select a format
- [ ] Briefly generally test other functionality of the Query Builder, such as: running old queries, selecting a different record formatter (https://github.com/specify/specify7/pull/4615), Query From Tree Node, etc.

2024-12-18 06:43 UTC, melton-jason commented on specifyweb/frontend/js_src/lib/components/QueryBuilder/reducer.ts
> -            : state.fields[line].dataObjFormatter,
Take a close look at this change @specify/dev-testing!
In my local testing, everything seems to work okay with this change, but I've yet to go deeper through the code and fully assess the consequences of the change.

2024-12-18 17:59 UTC, alesan99 requested changes
### Testing instructions
- [x] Ensure that by default, the Collection's default Catalog Number format is enforced 
- [c] Ensure the input of the field is now validating based on the format defined on the chosen Collection Object Type
- [x] Ensure each filter on the Catalog Number field with validation can independently have its own format
- [c] Save the Query and refresh the page: the Query should load successfully
- [x] Ensure the query returns correct results when using filters with multiple Catalog Number formats
- [x] If there is only one CollectionObjectType or all CollectionObjectTypes either don't specify a Catalog Number format or use the 
- [x] Briefly generally test other functionality of the Query Builder, such as: running old queries, selecting a different record formatter (https://github.com/specify/specify7/pull/4615), Query From Tree Node, etc.

---
The functionality looks good! 👍👍
I just have a minor note

If multiple COTs share the same formatter the selection dropdown always chooses the first one with that format. It's a little weird but the functionality works since it is the same formatter after all.
I imagine in practice most people will have a different formatter for each COT if they aren't sticking with the default, but if someone comes across this it may appear broken.

https://github.com/user-attachments/assets/b8ed934c-a1c7-4952-a316-9ddda6bb2a1b

The queries also not filtered very strictly and YEAR-###### includes ######## results, which is more noticeable when doing 'less than' queries.
Though this is in line with normal Catalog Number behavior and its easily solvable by adding COT to your query.

2024-12-18 18:47 UTC, CarolineDenis approved these changes

2024-12-18 19:03 UTC, sharadsw approved these changes

2024-12-20 15:41 UTC, alesan99 approved these changes
I've made a separate report for the issue I encountered -> https://github.com/specify/specify7/issues/5503

Looks good to go 👍👍👍

2024-12-20 16:08 UTC, acwhite211 approved these changes

2024-12-20 16:25 UTC, merged