Add better support for one-to-one relationships (COG/COJO Data Entry fixes)
specify/specify7 pull request #6018
Opened 2024-12-26 21:07 UTC by melton-jason

Fixes #5508
Fixes #5452
Somewhat Fixes #5463 (Save blocker is handled like any other required field: removing the COJO lets the user save) 

Mostly a reimplementation of https://github.com/specify/specify7/pull/5509 without serious consideration of Clone/CarryForward behavior

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good and
      self-explanatory (or properly documented)
- [ ] Add automated tests
- [ ] Add relevant issue to release milestone

### Testing instructions
For #5508: 
- Create or find a Collection Object Group 
- Add a child (COJO) to the Collection Object Group (COG) and save the COG
  - This can be either type of COJO child: Collection Object (CO) or another Collection Object Group
- [ ] Expand the child form on the COG (either CO or other COG), and ensure that changes and save-blockers "bubble" up to the primary COG form
  - i.e., make a change in a child form and ensure that you can save the parent form, and that any save blockers (like a uniqueness rule violation) prevents you from saving the parent form
- [ ] Save the COG and make sure that changes to any children are still bubbling up to COG form
- If not on the forms already, add the `cojo` relationship as a Subview to the CO or COG "base" Data Entry forms. 
- [ ] Go to the Data Entry form of a COJO child on the COG (either CO or COG) and make sure that the COJO displays correctly and changes to the COJO (and all related records to the COJO, i.e., COJO -> parentCog) propagate to the CO or COG. 
- [ ]  Save the CO or COG and make sure that changes to the COJO still propagate to the CO or COG

For #5452: 
- Create or find a Collection Object Group 
- Add a child (COJO) to the Collection Object Group (COG) and save the COG
  - This can be either type of COJO child: Collection Object (CO) or another Collection Object Group
- [ ] Go to the main Data Entry form of the COJO child you added to the COG (CO or COG), make a change, and save the form
- [ ] Go back the COG you created/found in step one (refresh the page if needed),  and make sure child is still associated with the COG

Please also do some general testing of subviews, both Independent and Dependent 🙏 : 
- Especially make sure the first Issue from https://github.com/specify/specify7/pull/5253#issuecomment-2334425790 can not be recreated
  - when editing both sides of a relationship as a subview (e.g., `CO -> accession` and `Accession -> collectionObjects`)
  - when making an edit when "distant" from the base form (e.g., making an edit in the last relationship of `CollectionObject -> determinations -> determiners -> agent`)
- It would also be nice to test the Issues which were mentioned as fixed in https://github.com/specify/specify7/pull/5253#issuecomment-2344003292!

2024-12-27 02:41 UTC, maxpatiiuk approved these changes

2024-12-27 18:43 UTC, alesan99 requested changes
### Testing instructions
For #5508: 
- [ ] Expand the child form on the COG (either CO or other COG), and ensure that changes and save-blockers "bubble" up to the primary COG form
- [x] Save the COG and make sure that changes to any children are still bubbling up to COG form
- [x] Go to the Data Entry form of a COJO child on the COG (either CO or COG) and make sure that the COJO displays correctly and changes to the COJO (and all related records to the COJO, i.e., COJO -> parentCog) propagate to the CO or COG. 
- [ ]  Save the CO or COG and make sure that changes to the COJO still propagate to the CO or COG

For #5452: 
- [x] Go to the main Data Entry form of the COJO child you added to the COG (CO or COG), make a change, and save the form
- [x] Go back the COG you created/found in step one (refresh the page if needed),  and make sure child is still associated with the COG

Please also do some general testing of subviews, both Independent and Dependent 🙏 : 
- [x] Especially make sure the first Issue from https://github.com/specify/specify7/pull/5253#issuecomment-2334425790 can not be recreated
  - [x] when editing both sides of a relationship as a subview (e.g., `CO -> accession` and `Accession -> collectionObjects`)
  - when making an edit when "distant" from the base form (e.g., making an edit in the last relationship of `CollectionObject -> determinations -> determiners -> agent`)
- It would also be nice to test the Issues which were mentioned as fixed in https://github.com/specify/specify7/pull/5253#issuecomment-2344003292!

---

On the COG form, making a change to a subview in a CO in the cojo subview does not propogate.

For example: Making a change to COG -> Cojo -> CO -> Determination does not re-enable the save button.

![image](https://github.com/user-attachments/assets/94c7e626-a925-400a-a6db-9180e0a42b53)

Also, in a COG form adding a COG parent does not add it as a child to the parent COG.

2024-12-30 15:16 UTC, melton-jason commented
> On the COG form, making a change to a subview in a CO in the cojo subview does not propogate.

This should be fixed now!

2024-12-30 18:00 UTC, alesan99 approved these changes
> This should be fixed now!

Yep that fixed it! 👌

2025-01-02 14:11 UTC, CarolineDenis approved these changes

2025-01-02 15:04 UTC, acwhite211 approved these changes

2025-01-02 16:18 UTC, melton-jason commented
Hi @specify/ux-testing! 

I think we are going to close #5509 in favor of this PR. 
This means that cloning, carry-forward, and bulk carry forward should be tested as well! 

Can the clone and carry-forward behavior be tested for COGs, COs, and COJOs? 

I've added the following testing instructions (taken from https://github.com/specify/specify7/pull/5509#issue-2753214588):  

> Test Cloning:
> - [ ] Select a CO form and add a parentCog to it in the Cojo subform.
> - [ ] Save the CO
> - [ ] Press the Clone button (no errors occur)
> - [ ] Verify that you can  save the new cloned CO and that the parent is present 
> - [ ] Verify it works for carry forward 
> - [ ] Verify it works for bulk carry

2025-01-02 19:33 UTC, pashiav requested changes
For #5508: 
- Create or find a Collection Object Group 
- Add a child (COJO) to the Collection Object Group (COG) and save the COG
  - This can be either type of COJO child: Collection Object (CO) or another Collection Object Group
- [ ] Expand the child form on the COG (either CO or other COG), and ensure that changes and save-blockers "bubble" up to the primary COG form
- [ ] Save the COG and make sure that changes to any children are still bubbling up to COG form
- [ ] Go to the Data Entry form of a COJO child on the COG (either CO or COG) and make sure that the COJO displays correctly and changes to the COJO (and all related records to the COJO, i.e., COJO -> parentCog) propagate to the CO or COG. 
- [ ]  Save the CO or COG and make sure that changes to the COJO still propagate to the CO or COG

For #5452: 
- [ ] Go to the main Data Entry form of the COJO child you added to the COG (CO or COG), make a change, and save the form
- [ ] Go back the COG you created/found in step one (refresh the page if needed),  and make sure child is still associated with the COG

Clone + Carry-Forward (from https://github.com/specify/specify7/pull/5509#issue-2753214588): 

Test Cloning:
- [ ] Select a CO form and add a parentCog to it in the Cojo subform.
- [ ] Save the CO
- [ ] Press the Clone button (no errors occur)
- [ ] Verify that you can  save the new cloned CO and that the parent is present 
- [ ] Verify it works for carry forward 
- [ ] Verify it works for bulk carry
---

Adding a COJO to a COG through query builder or by creating a new one causes an error upon saving.

https://ciscollections21524gen-issue-5508.test.specifysystems.org/specify/view/collectionobjectgroup/new
Collection: **Rocks**

[Specify 7 Crash Report - 2025-01-02T18_32_22.384Z.txt](https://github.com/user-attachments/files/18293796/Specify.7.Crash.Report.-.2025-01-02T18_32_22.384Z.txt)

2025-01-06 20:10 UTC, melton-jason commented
Hi @specify/ux-testing! 

> Adding a COJO to a COG through query builder or by creating a new one causes an error upon saving.

https://github.com/specify/specify7/pull/6018#pullrequestreview-2528114969

This has been fixed! 

_Workflow without error_

https://github.com/user-attachments/assets/fef0811b-de18-48c4-a197-27ff8f526f27

---

There was actually a relatively major issue with the API which I have fixed thanks to your testing efforts! 🕵️ 

Consider an example relationship of `CollectionObject -> cojo -> childCo`. In this example, the base CollectionObject and the `childCo` should always be the same CollectionObject:  because `cojo -> childCo` and `CollectionObject -> cojo`  are reverse relationships of each other. 

Another example of this could be `Accession -> collectionObjects -> accession`. Both the base Accession and the `accession` should be the same accession: there is no ambiguity. 

Just using `CollectionObject -> cojo -> childCo` as an example, you could use the API (also via the frontend), to send a request which creates or edits a `childCo` Collection Object (with its own data) then creates/updates the COJO and assigns the `childCo` to it, and _then_ creates the base CollectionObject and assigns the base CollectionObject to the COJO. 

_Before the fix_: 

https://github.com/user-attachments/assets/2fba6a19-ce6e-4b9b-91f1-359a7e316a70

I edited the cojo -> childCo here to highlight the problem. 
By not editing the `cojo -> childCo`, Specify would create a new CollectionObject, assign it to the COJO, and _then_ create the base CollectionObject! 

_After the fix_: 

https://github.com/user-attachments/assets/a9041780-74e2-4050-9979-ec442f26eae5

@specify/ux-testing 
The change was strictly done on the backend, so nothing visually has changed. If you have any ideas on how this can be made clearer to the user visually, feel free to share ideas and open Issues!

I think ideally any changes to a record in a relationship which is supposed to be identical to the base record should be reflected everywhere the record is present (on the same tab). 
e.g., When you edit the `CO -> cojo -> childCo` while on the CollectionObject form, any edits between the base and the `childCo` should be synced. 

@specify/dev-testing 
My solution to this is to always consider the "base" record as the canonical record, and if data is provided for a record which should be the same in the Datamodel, then ignore it. 
(e.g., ignore the `childCo` in `CO -> cojo -> childCo`) 

From an API behavioral standpoint, I don't think there's anything fundamentally wrong with the way it worked previously. There was no actual ambiguity with what the API was doing, but it might be confusing and/or very easy to mess something up. 
If we want to keep the previous behavior, we can instead move the logic/burden of trimming those relationships from the request to the frontend. Open for discussion!

2025-01-07 16:15 UTC, pashiav requested changes
### Testing instructions
For #5508: 
- [x] Expand the child form on the COG (either CO or other COG), and ensure that changes and save-blockers "bubble" up to the primary COG form
- [x] Save the COG and make sure that changes to any children are still bubbling up to COG form
- [x] Go to the Data Entry form of a COJO child on the COG (either CO or COG) and make sure that the COJO displays correctly and changes to the COJO (and all related records to the COJO, i.e., COJO -> parentCog) propagate to the CO or COG. 
- [X]  Save the CO or COG and make sure that changes to the COJO still propagate to the CO or COG

For #5452: 
- [x] Go to the main Data Entry form of the COJO child you added to the COG (CO or COG), make a change, and save the form
- [x] Go back the COG you created/found in step one (refresh the page if needed),  and make sure child is still associated with the COG

Test Cloning:
- [x] Select a CO form and add a parentCog to it in the Cojo subform.
- [x] Save the CO
- [x] Press the Clone button (no errors occur)
- [x] Verify that you can  save the new cloned CO and that the parent is present 
- [x] Verify it works for carry forward 
- [x] Verify it works for bulk carry
---
1. Error when adding Paleo Context to a child CO. Works in `production`.
	[Specify 7 Crash Report - 2025-01-07T15_20_46.691Z.txt](https://github.com/user-attachments/files/18335075/Specify.7.Crash.Report.-.2025-01-07T15_20_46.691Z.txt)

https://github.com/user-attachments/assets/dcf50704-469f-4f36-b387-dcea9fa2e8bf

<br>

2. Changing the cogType of a child COG doesn't save. Works in `production`.
I show the COG’s parent form, the COG’s form, and the COG’s form on production in the video.

https://github.com/user-attachments/assets/95050899-82a4-4246-b715-b7f311e2487b


Everything else looks good!!

2025-01-07 20:07 UTC, pashiav approved these changes
Issues for https://github.com/specify/specify7/pull/6018#pullrequestreview-2534792298 written up: https://github.com/specify/specify7/issues/6042 & https://github.com/specify/specify7/issues/6045

Everything else works!

2025-01-07 21:52 UTC, melton-jason commented
Thanks for the feedback and testing! 
There will be PR(s) open soon to address the Issues https://github.com/specify/specify7/issues/6040, https://github.com/specify/specify7/issues/6041, #6042 , and #6045

2025-01-07 21:52 UTC, merged